### ISSUE TITLE
Hooking a process is not working

### ISSUE THREAD

**Issue by halbbob** [EasyHook/EasyHook#100]
Hi all,
I am trying 2 hook a process (CClenaer). My app is as follow:

extern "C" int main(int argc, wchar_t* argv[])
{
std::wstring windowName= std::wstring(L"Piriform CCLeaner");// where Piriform CCLeaner is the window title of CClenaer
	HWND windowHandle = FindWindowW(NULL, windowName.c_str());
	DWORD* processID = new DWORD;
	GetWindowThreadProcessId(windowHandle, processID); 
	ULONG Pid=reinterpret_cast<signed long>(processID);
	std:: wcout << *processID;
	RhInjectLibrary(*processID, 0, EASYHOOK_INJECT_DEFAULT, L"TestDLL.dll", nullptr, NULL, 0);
     std::cin.get();
    return 0;
}

My DLL application defines the code inside the dllmain.cpp and as follow

// dllmain.cpp : Defines the entry point for the DLL application.
#include "easyhook.h"
#include "stdafx.h"
#include <iostream>

extern "C" void __declspec(dllexport) __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo);
#define DLL_EXPORT extern "C" __declspec(dllexport)

INT WINAPI DllMain(HMODULE hDLL, DWORD Reason, LPVOID Reserved){    
    switch(Reason){
    case DLL_PROCESS_ATTACH:
    case DLL_PROCESS_DETACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
        break;
    }
    return TRUE;
}

    
BOOL WINAPI myWriteFileHook(
  _In_        HANDLE       hFile,
  _In_        LPCVOID      lpBuffer,
  _In_        DWORD        nNumberOfBytesToWrite,
  _Out_opt_   LPDWORD      lpNumberOfBytesWritten,
  _Inout_opt_ LPOVERLAPPED lpOverlapped
);
BOOL WINAPI myWriteFileHook(
  _In_        HANDLE       hFile,
  _In_        LPCVOID      lpBuffer,
  _In_        DWORD        nNumberOfBytesToWrite,
  _Out_opt_   LPDWORD      lpNumberOfBytesWritten,
  _Inout_opt_ LPOVERLAPPED lpOverlapped
){
	
    TCHAR szTempFileName[260]=TEXT("Desert.jpg");
	std::cout << "\nHALBOOB";
	nNumberOfBytesToWrite=0;
	return WriteFile( hFile,lpBuffer,  nNumberOfBytesToWrite,lpNumberOfBytesWritten,lpOverlapped);
	 }

void __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo)
{

    HOOK_TRACE_INFO hHook = { NULL }; // keep track of our hook
    std::cout << "pBeep";
   
    std::cout << GetProcAddress(GetModuleHandle(TEXT("kernel32")), "WriteFile");
    
    
	// Install the hook
    NTSTATUS result = LhInstallHook(
        GetProcAddress(GetModuleHandle(TEXT("Kernel32")), "WriteFile"), 
		
        myWriteFileHook, 
		 NULL, 
        &hHook);
    if (FAILED(result))
    {
        std::wstring s(RtlGetLastErrorString());
        std:: wcout << "Failed to install hook: ";
        //std::wcout << s;
        std::cout << "\n\nPress any key to exit.";
        std::cin.get();
        //return 1;
    }
    
    std::cout << "Beep after hook installed but not enabled.\n";
    Beep(500, 500);

    std::cout << "Activating hook for current thread only.\n";
    // If the threadId in the ACL is set to 0, 
    // then internally EasyHook uses GetCurrentThreadId()
    ULONG ACLEntries[1] = { 0 };
    LhSetInclusiveACL(ACLEntries, 1, &hHook);

    std::cout << "Beep after hook enabled.\n";
    Beep(500, 500);

   std::cout << "Uninstall hook\n";
    LhUninstallHook(&hHook);

    std::cout << "Beep after hook uninstalled\n";
    Beep(500, 500);

    std::cout << "\n\nRestore ALL entry points of pending removals issued by LhUninstallHook()\n";
    LhWaitForPendingRemovals();
}

when I run I just receive the ProcessID printed by this statement 
std:: wcout << *processID;

Can anyone please let me know what wrong

**Comment by spazzarama** [comment]
Debug the target application as well and put a break point on your NativeInjectionEntry and make sure it is being called.

**Comment by halbbob** [comment]
Thanks dear ...how can I debug the target application? BTY, my code is well formed here http://stackoverflow.com/questions/37361699/hooking-a-process-using-easyhook-is-not-working
Could you please look at it and let me know if there is any other problems
Thank you so much for your attention and cooperation

**Comment by halbbob** [comment]
Hi dear
After debugging, I get this error
"the breakpoint will not currently be hit. the function cannot be found:NativeInjectionEntryPoint"
May be the problem is with the DLL could you please check the source
Regards

**Comment by maddin123** [comment]
Have the same problem, i have written an mail to spazza to provide an example for hooking native process remotely.

Regards

**Comment by halbbob** [comment]
In fact, debuging process gives me 2 issues
First, a message ""The breakpoint will not currently be hit. No symbols have been loaded for this document". When I click "Go to source code", the VS goes to "()" AT this code line
void __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo)
{

Another issue is the above which is:
"the breakpoint will not currently be hit. the function cannot be found:NativeInjectionEntryPoint"

**Comment by spazzarama** [comment]
@halbbob I moved your TestDLL.cpp into dllmain.cpp and then the export for NativeInjectionEntryPoint worked (not sure whats wrong with it in your original).

While debugging I had to specify the full path to the DLL to inject.

Hope this helps.
