### ISSUE TITLE
Hooked Com Function on Firefox crashes firefox.exe (most applications like vlc, chrome etc work)

### ISSUE THREAD

**Issue by polil91** [EasyHook/EasyHook#104]
Hello.
I am injecting  several applications and I am hooking a COM interface function on them in order to manipulate their audio outputs.
On most applications it works perfectly, but on latest firefox.exe it injects fine but when the hooked function is used it crashes.

The second issue I have is on some mmorpg games like BlackDesert where I get an error when injecting.

**Comment by spazzarama** [comment]
@polil91 can you hook any non-COM functions in firefox?

Some games implement additional anti-injection logic that might prevent injection from working. I haven't played BlackDesert so couldn't say whether it should work or not there...

**Comment by polil91** [comment]
Goodmorning
I just tried that and its intercepting CreateFileW fine.
firefox.exe does not crash as it is when intercepting a COM function.

I believe the problem is somewhere in the COMClassInfo

About BlackDesert i believe the same since its an MMORPG, there certainly exists a bypass but I can leave it aside at the moment.

Do you have any suggestions about the firefox?

Maybe if I could provide you a log of firefox to check?

**Comment by polil91** [comment]
Hi again,
Any ideas regarding my issue?

**Comment by spazzarama** [comment]
You will need to prepare a cutdown test case that you can share so it can be reproduced here.

**Comment by polil91** [comment]
Hi again.
Ok no problem I will prepare a console test and send it tomorrow.

**Comment by polil91** [comment]
Hi again.

I've made a test application that injects into the given application module name and hooks a COM function.
On vlc,chrome etc it works fine, but on firefox when you open youtube.com or another website that uses that function, it just crashes.

Please check it out and update me as soon as possible.

Thanks a lot.

[FirefoxInjectTest.zip](https://github.com/EasyHook/EasyHook/files/340256/FirefoxInjectTest.zip)

**Comment by polil91** [comment]
Hello spazzarama,
any updates on my issue?

**Comment by polil91** [comment]
Hi spazzarama
any updates on this issue?

**Comment by spazzarama** [comment]
Haven't had time to look at it yet

**Comment by polil91** [comment]
Oh ok, sorry if I was a bit annoying, take your time.

**Comment by spazzarama** [comment]
All good I just don't have a lot of spare time :)

**Comment by spazzarama** [comment]
@polil91 I was able to get this working by changing the signature to the following. Basically you need to use an IntPtr for the "this" parameter (you have it as vtablePtr) but also for the out going ppEndPoint (which I changed to out instead of ref).

To get the pointer to a COM object you use `Marshal.GetIUnknownForObject`.

```
        private int GetDefaultAudioEndpointHooked(IntPtr vtablePtr, DataFlow dataFlow, Role role, out IntPtr ppEndpoint)
        {
            IMMDeviceEnumerator enumerator = MMDeviceEnumeratorFactory.CreateInstance();

            //get default device refference
            IMMDevice defaultDevice;
            enumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Console, out defaultDevice);

            MessageBox.Show("hooked function run");
            ppEndpoint = Marshal.GetIUnknownForObject(defaultDevice);

            return 0;
        }
```

and 

```
[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
        delegate int GetDefaultAudioEndpointDelegate(IntPtr vtablePtr, DataFlow dataFlow, Role role, out IntPtr ppEndpoint);
```

**Comment by polil91** [comment]
OMG so that was it.
Weird though because on many other programs/games it worked fine.

Anyway I will do my testing when I get home.
I thank you very very much for your time and precious help.

**Comment by spazzarama** [comment]
No probs, good luck!

**Comment by spazzarama** [comment]
Btw - could it have been you were using 32-bit apps previously? You originally had an `int` whereas on 64-bit that would not fit. Another reason to ensure you use IntPtr for pointer types for these.

**Comment by polil91** [comment]
Well, vlc and chrome were x32, lords of the falled was x64 bit process. And firefox, (the one it crashed) was running x32 bit process.
The only thing I can think of is that it was running on x64 dll or something similar.
I will test again tonight and update you.

**Comment by polil91** [comment]
Update: Just tested changing the signature var to IntPtr and ref to out, everything seems to be working perfect on x86 and x64 apps.
I did not use Marshal.IUnknownForObject though because it returns the following error.
Cannot implicitly convert type 'System.IntPtr' to 'NAudio.CoreAudioApi.Interfaces.IMMDevice'

Thank you very very much for your help, you saved me from a lot of trouble, it didnt cross my mind that the sig could be wrong. (took it from a sample and assumed it was correct.)

Anyways thanks again.
