### ISSUE TITLE
MAX_HOOK_COUNT has wrong value on documentation

### ISSUE THREAD

**Issue by SammyROCK** [EasyHook/EasyHook#105]
Documentation for InsufficientMemoryException says MAX_HOOK_COUNT is currently set to 1024, but in fact it's 128 in code. Therefore InsufficientMemoryException is thrown way earlier than expected and causes a lot of confusion.

Example: https://easyhook.github.io/api/html/M_EasyHook_LocalHook_Create.htm

**Comment by spazzarama** [comment]
Pull request merged.
