### ISSUE TITLE
Can't use compiled from source easyhook's dll. Strange errors on compilation.

### ISSUE THREAD

**Issue by SocialShutdown** [EasyHook/EasyHook#107]
Hello, i'm trying to build your visual studio project with visual studio 2013 i got those two errors :

Error	4	The "DllExportAppDomainIsolatedTask" task could not be instantiated from "*****\EasyHook-2.7.5870.0\packages\UnmanagedExports.1.2.6\tools\RGiesecke.DllExport.MSBuild
RGiesecke.DllExport.MSBuild.dll". Could not load file or assembly 'RGiesecke.DllExport.MSBuild, Version=1.2.6.36228, Culture=neutral, PublicKeyToken=ad5f9f4a55b5020b' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)	EasyLoad

Error	5	The "DllExportAppDomainIsolatedTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.	EasyLoad

**Comment by spazzarama** [comment]
Could you make sure you have restored all NuGet packages first, sounds like it is missing...

**Comment by SocialShutdown** [comment]
It did install the Unmanaged Exports Dllexort for .net. But when i try to build the exact same error is thrown.

**Comment by SocialShutdown** [comment]
Okay, windows was blocking the dll, i unblocked it from property menu. If i try to replace the official easyhook dll by the recompiled ones in a project using easyhook. i get this : 
An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Impossible to load file or assembly 'EasyHook, Version=2.7.5870.0, Culture=neutral, PublicKeyToken=4b580fca19d0b0c5' or one of his dependencies. The definition in the manifest of the assembly don't match the assembly referencies. (Exception HRESULT : 0x80131040)

**Comment by spazzarama** [comment]
@SocialShutdown that usually happens if you haven't rebuilt all the projects - note the version number, that means whatever is linking to it is trying to get the specific version and not your newly built version (which would have a version number of 2.7.0.0 using default build).
