### ISSUE TITLE
hook game "overwatch" failed

### ISSUE THREAD

**Issue by dista** [EasyHook/EasyHook#109]
version 2.7.5870.1

The game path:
D:\Program Files (x86)\Overwatch\Overwatch.exe

Both FileMon and my own project use easyhook64.dll failed with:
"C++ completion routine has returned success but didn't raise the remote event." message

**Comment by spazzarama** [comment]
@dista if it works in other processes on the same machine it is possible that overwatch is employing an anti-injection technique.
