### ISSUE TITLE
Create C++ hooking example and tutorial

### ISSUE THREAD

**Issue by spazzarama** [EasyHook/EasyHook#11]
*Moved from [CodePlex](https://easyhook.codeplex.com/workitem/23034)
Originally submitted by spazzarama*

Create a complete C++ hooking example and update tutorial.

**Comment by majimboo** [comment]
Has this been implemented?

**Comment by spazzarama** [comment]
@majimboo not yet

**Comment by spazzarama** [comment]
@majimboo this is done.

See http://easyhook.github.io/tutorials.html
