### ISSUE TITLE
Can't get Visual Studio to crate easyHook64.dll

### ISSUE THREAD

**Issue by adal01** [EasyHook/EasyHook#110]
Thanks for this project it's great.

I have downloaded the Esayhook source files and got the entire solution to compile int Visual Studio community 2015.

The only problem I'm having is that I can't seem to get the the EasyHook64.dll file created. It does create a Easyhook.dll, but not a easyhook64.dll.

I get an error when trying to run the filemon.exe sample. "Unable to load easyhook64.dll".

I noticed the binaries for the version seem to have the easyhook64.dll already. 

I wonder if I have some kind of bad Visual Studio Setting. I have tried compiling the whole solution for all targets and did a "Rebuild all" but no luck.

Any help on this issue would be great!!

**Comment by spazzarama** [comment]
You need to build win32 and x64 configurations, ie build one then the other - there are post build events to copy files to appropriate locations. Build.bat builds them all for you

**Comment by adal01** [comment]
Thanks for the response...

I tried building the Easyhookdll visual studio project, targeting the 32bit, then the 64bit platform like you suggested..
I get a linker error with the compiler looking for the "Aux_ulib_x86.lib" for the 32bit platform, and the "Aux_ulib_x64.lib" for the 64bit platform.

I did a search on my entire system and those files don't exist anywhere.

At this point I still can't create a easyhook32.dll or a easyhook64.dll.

I'm sure I must be missing something simple.

**Comment by spazzarama** [comment]
They are both in the EasyHookDll project path, e.g. \EasyHook\EasyHookDll

**Comment by spazzarama** [comment]
Perhaps make sure you have a fresh copy and run build.bat

**Comment by adal01** [comment]
I have tried using multiple versions of visual studio to get a clean build (2013 and 2015). I get different build errors and missing files. 

I was wondering if you could tell me what version of Easyhooks is best to use and what version of Visual studio you build that version with. 

I noticed in the VS 2013 express version it fails looking for <altbase.h>. Maybe because it's express and not professional?

Anyways my goal is to get a Easyhooks version to compile and run using Visual Studio 2015 community edition.  Currently with that VS version I get the problem with the  "Aux_ulib_x86.lib" missing when trying to build the Easyhook32.Dll or Easyhook64.Dll

Thanks in advance for any advice.

**Comment by spazzarama** [comment]
I use visual studio 2015, not community edition. Please let me know how you go.

**Comment by adal01** [comment]
Hi Justin,

I'm going to try using Visual Studio 2015 Professional Version that I have at work.  I will try it with the latest EasyHooks Beta release that you have out on Github. Is that the correct EasyHooksrelease that I should be using, or do you suggest another version that might be more stable?

My end goal is to to try and capture text from other programs by using Easyhooks, and hooking the TextOut Win32 API's . Have you done this before with EasyHooks? If so do you have any sample code?

I will report back and let you know how things turn out trying to compile on Visual Studio 2015 Pro.

Have a great day, and again thanks for maintaining this project. It's a great project!

**Comment by spazzarama** [comment]
Others have hooked the TextOut Win32 API's.

**Comment by adal01** [comment]
Everything compiles fine on VS professional.

Thanks for all the help.

**Comment by TechnikEmpire** [comment]
Can this process not change? Should just dump both of them into the directory and dynamically resolve which one to load, or embed them into the existing arch-specific directories and then dynamically modify the executing assembly's path environment to include both dirs and let the .NET loader handle it automatically.
