### ISSUE TITLE
Hooking only 32bit app on 64/32 bit machines

### ISSUE THREAD

**Issue by adal01** [EasyHook/EasyHook#124]
I have a project where I only need to hook a specific application that is 32bit. The application may run on both 32/64 bit windows machines.

I would like to distribute the lest amount of EasyHook redistribution binaries.

Is there a way to NOT distribute the 

EasyHook64.dll, 
EasyHook64SVC.dll, 

It appears I can leave out the EasyHook64Svc.dll, but NOT the EasyHook64.dll.

Are there others binary distribution files I can leave out somehow?

Thanks in advance
Allen

**Comment by spazzarama** [comment]
If you force your app to be 32-bit instead of AnyCPU or 64-bit then you can drop the 64-bit variety of all binaries. EasyLoad64 is only used in the target so you can drop that either way. 

Again if your app is 32-bit you don't need the easyhook32svc.exe either.

**Comment by adal01** [comment]
Thanks for the response, and thanks for such a great project.
