### ISSUE TITLE
User library not strongly named!  ERROR

### ISSUE THREAD

**Issue by adal01** [EasyHook/EasyHook#125]
Hello,

I'm getting an error when I try to replace the demo program FileMon.exe with my own Winforms program.

I replaced the demo filemon.exe with my own Winform application "PCTextCapture.exe". It does the same thing as filemon.exe. Loads the FileMonInject.dll into the target process.

When I try to hook the target process by  loading the fileMonInject.dll from my Winfomr application "PCTextCapture.exe" I get an error on the Config.Register(.....) call as seen below. 

HERE IS THE ERROR FROM TRYING TO CALL CONFIG.REGISTER(....) 
_"**The given user library \"PCTextCapture.exe\" is not strongly named!"	string_**

BELOW IS THE CODE SNIPPET THAT THROWS THE ERROR 
try
            {
                // INSTALL THE TEXT CAPTURE HOOK
                Config.Register(
                       "A FileMon like demo application.",
                       "PCTextCapture.exe",
                       "FileMonInject.dll");

                RemoteHooking.IpcCreateServer<FileMonInterface>(ref m_ChannelName, WellKnownObjectMode.SingleCall);

                RemoteHooking.Inject(
                    m_TargetPID,
                    "FileMonInject.dll",
                    "FileMonInject.dll",
                    m_ChannelName);
            }

Thanks for providing such a great project!!!

**Comment by spazzarama** [comment]
Check the options for RemoteHooking.Inject, one of the flags means "Do not require strong names".

**Comment by spazzarama** [comment]
Oh and in that case you won't want to use Config.Register at all.

**Comment by adal01** [comment]
Thanks for the quick response it worked fine.
