### ISSUE TITLE
Inject native dll with managed application

### ISSUE THREAD

**Issue by IgnisDivine** [EasyHook/EasyHook#129]
Hello. I have some dll written on c++ and want to inject it to some process with managed application(c# for ex.). Can I do this with easyhook?

**Comment by spazzarama** [comment]
@IgnisDivine yes this is possible, however you have to implement the EasyHook native export in your DLL (see the Native Remote hook tutorial: http://easyhook.github.io/tutorials/nativeremotehook.html )
