### ISSUE TITLE
IPC Port: Access is denied ERROR (Continued from Issue #126)

### ISSUE THREAD

**Issue by adal01** [EasyHook/EasyHook#130]
When I make the call below I get the the following error.
"Failed to connect to an IPC Port: Access is denied.\r\n "

RemoteHooking.Inject(
m_TargetPID,
"FileMonInject.dll",
"FileMonInject.dll",
m_ChannelName);

I DID NOT get this error when I ran the demo Filemon.exe, but now that I have replaced the filemon.exe with my own program PCTextCatpure.exe I now get the error.

I get the same error at home and on my work machine. At this point I don't think it is a computer rights issue,  more of an issue with the settings in the original demo project Filemon.exe. Could this have something to do with signing the project?

I anyone out there has solved this issue please share. Thanks in advance.

For more details see issue #126.

**Comment by spazzarama** [comment]
See #126
