### ISSUE TITLE
EasyHook64.DLL is flagged as virus by Symantec

### ISSUE THREAD

**Issue by Pyre909** [EasyHook/EasyHook#133]
Just FYI,

It seems that Easyhook64.dll is being flagged as malware by my antivirus. Unfortunately I cannot uninstall it. 

What I have been doing to keep it working is just redropping it into the directory where it is being used after every restart as the antivirus removes it during startup. This only happens when the antivirus does the scans.

**Comment by spazzarama** [comment]
Thanks Steve, I'll sign the next binary, hopefully that will help prevent the official release being abused. Other than that I don't think there will be much I can do.
