### ISSUE TITLE
First attempt at hooking doesn't seem to work.

### ISSUE THREAD

**Issue by huckleberrypie** [EasyHook/EasyHook#134]
First and foremost you'll have to bear with me as I am more or less new to this stuff. I'm just trying to fix an API issue with an old game I have. Now on to the problem: I'm trying to adapt code from the C++ Easyhook tutorial so that it will override CreateWindowExA into using NULL for hMenu:
http://pastebin.com/rVcDmwuY

Problem is while the project does compile to a DLL, and it does appear to load using an ASI loader (you know, like the ones used for GTA games), it doesn't appear to be able to override the said function. Am I doing it wrong with the code?

**Comment by spazzarama** [comment]
You are using SetInclusiveACL which prevents any other thread from being intercepted, instead use SetExclusiveACL

**Comment by huckleberrypie** [comment]
Are there anything else I need to fix besides the ACL stuff? Tried using SetExclusiveACL to no avail. :/

**Comment by spazzarama** [comment]
You are uninstalling the hook immediately

**Comment by huckleberrypie** [comment]
How do I make sure that it doesn't unhook as such then?

**Comment by spazzarama** [comment]
Don't call LhUninstallHook :)

**Comment by huckleberrypie** [comment]
OK, noted.

**Comment by huckleberrypie** [comment]
Hmm, still no dice.

**Comment by spazzarama** [comment]
Could you talk through how you are trying to use this currently? Or how you would like to be using it? I think probably just a step is being missed but I'm not sure of the context in which u are using it.

In the current process? Or in another process with injection? The snippet you have pasted doesn't do anything in dllattach and if it is the app the main function doesn't actually end up calling CreateWindowExA so your hook would never be called.

Your "myWundowHook" should probably be calling CreateWindowExA to call the original function, passing your modified parameter through or whatever you need to do in it.

Hope this helps

**Comment by spazzarama** [comment]
Also if this is with injection, have you seen the remote hook tutorial?

**Comment by huckleberrypie** [comment]
Yes I'm using EasyHook on a DLL to which I am injecting to a game in order to fix an issue, similar to this thread on GTAForums:
http://gtaforums.com/topic/517994-creating-asi-files-for-gta-sa/

I hope you don't mind if you can chat with me for a while so I can explain things more thoroughly regarding my problem.

**Comment by huckleberrypie** [comment]
Hmm, guess I might as well rewrite things then. I think i can more or less figure things out now. ;)

**Comment by spazzarama** [comment]
Good luck

**Comment by huckleberrypie** [comment]
Thanks!
