### ISSUE TITLE
Hook gdi32 function D3DKMTCreateContextVirtual will crash, Windows 10 + WOW64+NVIDIA GFX only

### ISSUE THREAD

**Issue by ivellioscolin** [EasyHook/EasyHook#135]
Initial debug shows the stack is corrupted.

Easy to reproduce with modified DX11 demo "Tutorial01".

"GetProcAddress(GetModuleHandle(TEXT("gdi32")), "D3DKMTCreateContextVirtual")"

**Comment by spazzarama** [comment]
You may also need to show your hook handler function signature and that of the delegate as this could also cause issues.

**Comment by ivellioscolin** [comment]
Sample attached.
[Tutorial01.zip](https://github.com/EasyHook/EasyHook/files/422348/Tutorial01.zip)

Someone can have a try on 64bit OS whiling compile and run the 32bit app.

**Comment by ivellioscolin** [comment]
Root cause addressed. I didn't handle calling convention correctly.
