### ISSUE TITLE
Remote Hooking with C#

### ISSUE THREAD

**Issue by GabrielTK** [EasyHook/EasyHook#154]
Good Evening,
I was looking at EasyHook and I think it would be nice to use it in some projects. Does anybody have any tutorial about using Remote Hooking with C# (if it is possible)?? I tried to follow [this tutorial](https://leakforums.net/thread-486769), but I think it is a bit confusing, as I don't need IPC,... (I just need to hook the function used for getting the windows time/date.
Thank you,
Gabriel

**Comment by spazzarama** [comment]
@GabrielTK that tutorial is fine, just skip adding the channel name parameter, and don't create the channel. Otherwise you still have to create the IEntryPoint etc...

**Comment by GabrielTK** [comment]
OK, thx. Just one more question: what are this Marshal and Delegate things??

**Comment by spazzarama** [comment]
Marshal class is used to marshal memory between managed and native.

Delegate can be thought of as a function pointer (kinda). Both are critical to hooking native methods and you need to get these correct or exceptions / crashes may occur.

**Comment by GabrielTK** [comment]
Ok, last question: If I create the DLL with C++ and the injector in C#, am I going to get any problem?
