### ISSUE TITLE
Native API Hook - retrieve trampoline bypass address

### ISSUE THREAD

**Issue by rramk** [EasyHook/EasyHook#155]
This is an enhancement request, follow up from [https://github.com/EasyHook/EasyHook/issues/152](url), to expose "OldProc" member in an accessible manner.

**Comment by rramk** [comment]
Hi @spazzarama Can you kindly tell an estimated date when the 2.8 milestone/version would be released??

**Comment by rramk** [comment]
@spazzarama , Can you please comment on the estimated release date of 2.8 milestone ??

**Comment by spazzarama** [comment]
@rramk I've started changes for 2.8. I should have them completed within a few weeks.

**Comment by spazzarama** [comment]
@rramk there is a pre-release build with this fix on appveyor if you want to try it.

https://ci.appveyor.com/project/spazzarama/easyhook/build/0.0.31/artifacts

Check the unit test for usage:
https://github.com/EasyHook/EasyHook/blob/develop/Test/EasyHook.Tests/LocalHookTests.cs#L120

**Comment by rramk** [comment]
@spazzarama, the fix works with the pre-release 2.7.6251.0 binaries. Thank you. So, by when can I expect the 2.8 stable binaries?

**Comment by spazzarama** [comment]
@rramk thanks for checking out the fix. I'm not sure exactly when I will get a 2.8 release done, as there are quite a few tasks for that release. I'll look at doing a new 2.7 release with this change instead as it is fairly minor.

**Comment by rramk** [comment]
That would be great. Thanks. So, Can I know the expected date for the 2.7 release with this fix?

**Comment by spazzarama** [comment]
Nuget released
