### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 564064202** [EasyHook/EasyHook#157]
Dear sir ,this project is great,but the document is too bad,too less.
Can you write a completely document which can be Understood by anyone.
I think this document will help too many people (and you)

**Comment by spazzarama** [comment]
The problem here is "understood by anyone". 

I will continue to add tutorials and so on, but unfortunately I don't have oodles of time to spend on this. 

Feel free to suggest specific areas that you would like to see expanded upon.

**Comment by 564064202** [comment]
I am so sorry to hear that.May you will have enough time .
you can write some demos that can be understood by a newer

**Comment by spazzarama** [comment]
@564064202 have you taken a look at the tutorials and documentation found on http://easyhook.github.io ?

**Comment by 564064202** [comment]
But I have not found any documents describe how to use id.
Just find one demo,api.................

**Comment by spazzarama** [comment]
So you looked at the tutorial on creating a local hook? http://easyhook.github.io/tutorials/createlocalhook.html

**Comment by 564064202** [comment]
you can write some demos combine which api

**Comment by 564064202** [comment]
all right.
