### ISSUE TITLE
Injecting assembly into application using EasyHook internally (eg Unreal Engine 3) description

### ISSUE THREAD

**Issue by spazzarama** [EasyHook/EasyHook#16]
*Moved from [CodePlex](https://easyhook.codeplex.com/workitem/25390)
Originally submitted by capenl*

Hi,
I'm having a strange issue injecting an assembly into applications using Unreal Engine 3. It works if I use a C++/CLI injection library, but if I write a C# library, my application crashes upon trying to inject. I get a `"STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 14)"`

In both cases, I'm calling EasyHook from a C# assembly, but there is some difference in the method I use in EasyHook. For the C++/CLI library I use NativeAPI.RhInjectLibrary(), like this:
`NativeAPI.RhInjectLibrary(ProcessInfo.ProcessId, 0, 0, dllName, dllName, intPtr.AddrOfPinnedObject(), (int)ms.Length);`
Where ms is a MemoryStream to which I serialize the data I want to pass over, and intPtr is the pointer to the corresponding buffer (`GCHandle.Alloc(ms.GetBuffer(), GCHandleType.Pinned);`)

In the C# assembly I use RemoteHooking.Inject, like this:
RemoteHooking.Inject(ProcessInfo.ProcessId, dllName, dllName, injectionData);
Here injectionData is the data as an object, not serialized.

So, to reiterate, for most processes, both approaches work, but for Unreal Engine 3-games, only the C++/CLI version works. Any idea why? Am I doing something wrong? I'm using EasyHook version 2.7.5159, and my .NET projects target CLR 4.5.

Best regards,
Carl

**Comments**

*Temaran wrote Apr 2 at 10:29 PM*

Hello Spazzarama! 

I am working with this now instead of capenl, and it seems like we are still experiencing similar errors here. 

I've been running my tests with this workflow:
 1. Get the latest 2.7 release branch snapshot
 2. Build the netfx4.0-release configuration for both Win32, x64 and AnyCPU to get all binaries.
 3. Run the samples and try to inject into different targets

Some things seem to be working, some don't.

When running the AnyCPU ProcessMonitor for example it almost always throws the `"STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)"` error, no matter the process. 
Sometimes it also throws because of `STATUS_INTERNAL_ERROR: Unable to find EasyHook library in target process context. (Code: 5)`. If I try to inject into chrome.exe for example I get this. 

Now, if I instead build the netfx3.5 release, it works for almost all processes, except for a few. One is the SCNotification.exe process (not sure what this is, but it seems related to showing adverts) and also another process that is inhouse. Both of these processes are running .net 4.0, and throw `"STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)"` 

I don't think this matters much for us though, since we aren't really interested in injecting into any of these, but it might be interesting to find out why these processes cannot be injected into. 

Best regards,
Temaran

**Comment by Symbai** [comment]
I have the same issue. On the first computer (WIndows 8.1) it works perfectly and the second computer (Windows 8.1) it does not. Tried several DX games (9,10,11) with or without steam but always code 15.

**Comment by spazzarama** [comment]
@Symbai code 15 means it was unable to install the EasyLoad32/64.dll and then call the `Loader.Load` export for some reason. Usually this is because the target is incompatible with the .NET version you are using (i.e. try .NET 3.5 instead of .NET 4 or vice versa). 

Why it works on one computer vs another is a bit odd however... Can you confirm that the files are not being blocked due to being downloaded from Internet Explorer?

**Comment by spazzarama** [comment]
@Symbai There is another situation where Code 15 occurs, which is if the AppDomain.CreateDomain fails within EasyLoad32/64.dll.

I have found that AppDomain.CreateDomain will fail with an OutOfMemoryException when the executable stack commit size is larger than or equal to approximately 0x40000 (on my machine anyway). This can occur because native linking allows the developer to specify the stack reserve and commit size.

Anyway you can check this using dumpbin.exe nameof.exe /headers.

I'll be working on a fix that reverts to not using a new AppDomain if this occurs.

**Comment by spazzarama** [comment]
@Symbai I've just made a new release v2.7.5870.0 that hopefully addresses the issue, please let me know if it helps.

**Comment by Symbai** [comment]
No it doesn't fix the issue. I can hook into any Win32 process but Win64 I get error code 15. When using the TestFuncHook.exe I get:

memory.c !IsBadReadPtr(intptr,insize)

**Comment by kogodm** [comment]
same issue,my code can inject successd in debug mode,but not working in release mode.
after i change the hook dll and injector target from .net 4.5.2 to .net 4,fixed.

**Comment by kogodm** [comment]
same issue again,but this time,i find the point.
i attack the target process,and see the "EsayLoad.dll" still loaded in the target process,when i inject again,get error code 15. wish for help

**Comment by svgai** [comment]
Hi all, had same issue and was able to resolve it. I'm not sure my root cause is the same as everybody else's but may be it'll be helpful.

In my specific case, I was hooking binaries that was located under same directory that hooking dlls. Let's say, I'm hooking executable foo.exe located under mytools/, that has EasyHook.dll as well. Meanwhile, I tried to build (successfully) another version of hooking API, located under mytools2/ and tried to hook executable mytools/foo.exe. So I had same runtime error that all of you.

Removing EasyHook dll from executable directory solved the problem (still error message was very cryptic and all I saw and googled regarding it was super misleading, so I think it's a pure luck). 

My guess that the problem in order of directory traversal. Despite the fact I'm using hooking from mytool2, it's trying to appdomain is trying to register executable in the same directory mytool/ (I think it's the traversal priority) and discovers that library is already registered (the one from mytools2/). 

By the way, it would be super helpful to have at least some clue in exception message (regarding appdomain, for example). That would have save me several hours at least, 

Sincerely,
Svetlana

**Comment by thopiddock** [comment]
Thank you @svgai - this pointed me toward finding the NuGet packages had been reinstalled and embedded into the target Injected assembly, causing the duplicate executable.

Double check the NuGet packages you have installed on your Host and Target assemblies as some EasyHook Packages include these executables.

Regards,
Tom

**Comment by QGB** [comment]
```
---------------------------
          switch (NtStatus = NativeAPI.RhInjectLibraryEx(
                            InTargetPID,
                            InWakeUpTID,
                            NativeAPI.EASYHOOK_INJECT_MANAGED | InNativeOptions,
                            Path.Combine(Config.HelperLibraryLocation, "EasyLoad32.dll"),
                            Path.Combine(Config.HelperLibraryLocation, "EasyLoad64.dll"),
                            hPassThru.AddrOfPinnedObject(),
                            (int)PassThru.Length))
---------------------------

0: 9608
1: 0
2: 536870913
3: C:\test\easyhook\EasyHook\Build\netfx3.5-Release\x64\EasyLoad32.dll
4: C:\test\easyhook\EasyHook\Build\netfx3.5-Release\x64\EasyLoad64.dll
5: 38317032
6: 507
---------------------------
确定   
---------------------------


```

**Comment by QGB** [comment]
```

Usage: FileMon %PID%
   or: FileMon PathToExecutable

Please enter a process Id or path to executable: 9608
There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   在 EasyHook.NativeAPI.Force(Int32 InErrorCode) 位置 C:\test\taobao\easyhook\EasyHook\EasyHook\DllImport.cs:行号 487
   在 EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs) 位置 C:\test\taobao\easyhook\EasyHook\EasyHook\RemoteHook.cs:行号 736
   在 FileMon.Program.Main(String[] args) 位置 C:\test\taobao\easyhook\EasyHook\Examples\FileMon\Program.cs:行号 87
<Press any key to exit>

```
