### ISSUE TITLE
Windows 10 - some apps don't work + some weird issues

### ISSUE THREAD

**Issue by goranambardziev** [EasyHook/EasyHook#164]
Hello,

I've been using the latest binaries v2.7.6035.0 on Windows 10, and I've got some weird results using Process Monitor.

For example, if I monitor Winamp it works without problem. But if I monitor Windows Media Player, it installs hook OK but I don't receive CreateFile callbacks. No errors reported.

And the most weird issue is when using program called Raduga. When monitoring Raduga, I get CreateFile callback when wav or other type of files are opened, but not when mp3 is opened!?

In all of the previous situations, I can see that CreateFile is used (I monitor this by using Process Monitor from sysinternals, which successfully logs all actions)

Anybody experienced this kind of problems?

Thanks.

**Comment by Evengard** [comment]
Hook CreateFileExW instead of CreateFile.

**Comment by spazzarama** [comment]
@Evengard @goranambardziev the process monitor should already be hooking CreateFileW.

**Comment by goranambardziev** [comment]
@Evengard @spazzarama Yes, CreateFileW was hooked, You inspired me to hook CreateFileA signature and NtCreateFile, too.

Now when running Winamp, I can see CreateFileW call, after which immediately follows NtCreateFile call (which is normal, since CreateFileW calls NtCreateFile inside).

Now I can see files opened with NtCreateFile in Windows Media Player.  I don't get CreateFileW calls which is odd. Only NtCreateFile. However, when first file is opened I get "The caller is not inside a hook handler." for CreateFileW_Hooked and NtCreateFile_Hooked callbacks. Then, subsequent calls to NtCreateFile does not throw that error? CreateFileW is not called anymore.
