### ISSUE TITLE
How to use easyhook to global hook

### ISSUE THREAD

**Issue by BackTrackCRoot** [EasyHook/EasyHook#165]
I want to hook any process to call MessageBoxA, but the Doc isn't circumstantial. Can you give me some ideas or example? Thanks!

**Comment by spazzarama** [comment]
@BackTrackCRoot EasyHook is primarily designed for targeting specific processes. 

It is possible to use the EasyHook driver project to catch all processes but there is little or no support for this (perhaps someone in the community may be able to assist). For security software this is probably the approach to pursue.

Without the driver approach you would have to periodically monitor all processes and inject into any new ones from your host process. However this will not work very well for hooks where you need to be injected early, and is not suitable for building security related solutions.

**Comment by BackTrackCRoot** [comment]
Thanks for your help. I had thought EasyHook support global hook,but i got to know it can't support. I try to use Registry to inject or other way. Thanks!
