### ISSUE TITLE
A good article in codeproject , i hope it can add to document.

### ISSUE THREAD

**Issue by BackTrackCRoot** [EasyHook/EasyHook#169]
In EasyHook Document , it only wrote how to create local hook. however ,it can't tell us how to create remote hook in C#. so i think it can help more pepole.

article link: https://www.codeproject.com/articles/27637/easyhook-the-reinvention-of-windows-api-hooking

**Comment by 564064202** [comment]
thanks , the author should help us knowing how to use it in remote hook

**Comment by spazzarama** [comment]
I'm now working on an updated managed remote hooking tutorial for https://easyhook.github.io

**Comment by 564064202** [comment]
@spazzarama thanks,please notice us when it's done

**Comment by spazzarama** [comment]
An updated tutorial has been added here: http://easyhook.github.io/tutorials/remotefilemonitor.html

You will find the source code for this example at: https://github.com/EasyHook/EasyHook-Tutorials/tree/master/Managed/RemoteFileMonitor

**Comment by BackTrackCRoot** [comment]
thanks~
