### ISSUE TITLE
CRT Debug Assertion Failed - "Buffer too small"

### ISSUE THREAD

**Issue by ChristianIvicevic** [EasyHook/EasyHook#170]
I have an injector which calls the following (shortened) code:
```csharp
var processes = Process.GetProcessesByName("target");
/* ... */
var process = processes[0];
/* ... */
process.Kill();
RemoteHooking.CreateAndInject(process.MainModule.FileName, string.Empty, 0,
    InjectionOptions.NoService | InjectionOptions.DoNotRequireStrongName,
    typeof(EntryPoint).Assembly.Location, typeof(EntryPoint).Assembly.Location,
    out injectedProcessId, null);
```
The corresponding DLL just has the following:
```csharp
public class EntryPoint : IEntryPoint {
    public EntryPoint(RemoteHooking.IContext InContext) {}

    public void Run(RemoteHooking.IContext InContext) {
        RemoteHooking.WakeUpProcess();
        Thread.Sleep(5000);
    }
}
```
Unfortunately when running with the NuGet libraries the injector just crashes with the typical Windows Error Reporting tool showing up and no visual exception message at all. The error from the Event View is this one:
```
Faulting application name: TestInjector.vshost.exe, version: 14.0.23107.0, time stamp: 0x559b788a
Faulting module name: EasyHook64.dll, version: 2.7.0.0, time stamp: 0x589704aa
Exception code: 0xc0000409
Fault offset: 0x0000000000091a9b
```
When running in debug mode, I am not able to step through the EasyHook code step by step, but I am getting at least one exception

![](https://puu.sh/tPfoS.png)

Do you have any suggestions on how to further debug this issue and find out what's causing it?

**Comment by ChristianIvicevic** [comment]
I could resolve the error - the application that I was invoking was getting a command line argument as well (which is not in my sample code unfortunately) which is too long for the library. Therefore I increased the buffer size [right here](https://github.com/EasyHook/EasyHook/blob/master/EasyHookDll/RemoteHook/thread.c#L504) as well as the referring call to it [right here](https://github.com/EasyHook/EasyHook/blob/master/EasyHookDll/RemoteHook/thread.c#L529) and it works now without any issues.

**Comment by spazzarama** [comment]
This has also been fixed on the Develop branch
