### ISSUE TITLE
C# module unloaded after injected

### ISSUE THREAD

**Issue by spyware293** [EasyHook/EasyHook#171]
My dll just unloaded after it's successfully injected. This is my run() code

> public void Run(RemoteHooking.IContext InContext, String inChannelName)
>         {
>             try
>             {
>                 MessageBox.Show("success");
>                 Winsock_Recv = LocalHook.Create(LocalHook.GetProcAddress("ws2_32.dll", "recv"), new recvw(myrecv), this);
>                 Winsock_Recv.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
>                 Winsock_Send = LocalHook.Create(LocalHook.GetProcAddress("ws2_32.dll", "send"), new sendw(mysend), this);
>                 Winsock_Send.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
>             }
>             catch
>             {
>                 MessageBox.Show("fail");
>             }
>         }

Messagebox (success) shows up and then dll unloaded. Do i need to create endless loop?

**Comment by spazzarama** [comment]
Endless loop (with sleep), WaitEventHandle or similar.
