### ISSUE TITLE
The given user library does not export a proper class1

### ISSUE THREAD

**Issue by Boudat** [EasyHook/EasyHook#179]
![image](https://cloud.githubusercontent.com/assets/28234188/25570202/4ce93b0e-2e55-11e7-8dc2-6aaaf01ec1be.png)
This is my class1
![image](https://cloud.githubusercontent.com/assets/28234188/25570212/5c94b290-2e55-11e7-9af8-315f03042f82.png)

Im following this tutorial
https://leakforums.net/thread-486769?tid=486769&&pq=1

**Comment by spazzarama** [comment]
You may want to take another look at that tutorial, you are missing the constructor(s) and Run method in class1 (if that is meant to be the EasyHook.IEntryPoint)

**Comment by spazzarama** [comment]
Or is there more code you have not posted? Probably best to post the whole class if you want help

**Comment by Boudat** [comment]
> namespace FileMonitorHook
{
    public class Class1 : EasyHook.IEntryPoint
    {
        [DllImport("kernel32.dll", CharSet = CharSet.Ansi, SetLastError = true)]
        public static extern IntPtr CreateFileA(
             [MarshalAs(UnmanagedType.LPStr)] string filename,
             [MarshalAs(UnmanagedType.U4)] FileAccess access,
             [MarshalAs(UnmanagedType.U4)] FileShare share,
             IntPtr securityAttributes,
             [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
             [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
             IntPtr templateFile);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        public static extern IntPtr CreateFileW(
             [MarshalAs(UnmanagedType.LPWStr)] string filename,
             [MarshalAs(UnmanagedType.U4)] FileAccess access,
             [MarshalAs(UnmanagedType.U4)] FileShare share,
             IntPtr securityAttributes,
             [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
             [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
             IntPtr templateFile);
        [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
        public delegate IntPtr TCreateFileW(
        [MarshalAs(UnmanagedType.LPWStr)] string filename,
             [MarshalAs(UnmanagedType.U4)] FileAccess access,
             [MarshalAs(UnmanagedType.U4)] FileShare share,
             IntPtr securityAttributes,
             [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
             [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
             IntPtr templateFile);

        [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi, SetLastError = true)]
        public delegate IntPtr TCreateFileA(
        [MarshalAs(UnmanagedType.LPStr)] string filename,
            [MarshalAs(UnmanagedType.U4)] FileAccess access,
            [MarshalAs(UnmanagedType.U4)] FileShare share,
            IntPtr securityAttributes,
            [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
            [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
            IntPtr templateFile);

        static IntPtr hkCreateFileW([MarshalAs(UnmanagedType.LPWStr)] string filename,
            [MarshalAs(UnmanagedType.U4)] FileAccess access,
            [MarshalAs(UnmanagedType.U4)] FileShare share,
            IntPtr securityAttributes,
            [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
            [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
            IntPtr templateFile)
        {
            try
            {
                ((Class1)HookRuntimeInfo.Callback).Interface.GotFileNameW(filename);
                return CreateFileW(filename,access,share,securityAttributes,creationDisposition,flagsAndAttributes,templateFile);
            }
            catch(Exception ex)
            {
                ((Class1)HookRuntimeInfo.Callback).Interface.ErrorHandler(ex);
                return IntPtr.Zero;
            }
        }

        static IntPtr hkCreateFileA([MarshalAs(UnmanagedType.LPWStr)] string filename,
            [MarshalAs(UnmanagedType.U4)] FileAccess access,
            [MarshalAs(UnmanagedType.U4)] FileShare share,
            IntPtr securityAttributes,
            [MarshalAs(UnmanagedType.U4)] FileMode creationDisposition,
            [MarshalAs(UnmanagedType.U4)] FileAttributes flagsAndAttributes,
            IntPtr templateFile)
        {
            try
            {
                ((Class1)HookRuntimeInfo.Callback).Interface.GotFileNameA(filename);
                return CreateFileA(filename, access, share, securityAttributes, creationDisposition, flagsAndAttributes, templateFile);
            }
            catch (Exception ex)
            {
                ((Class1)HookRuntimeInfo.Callback).Interface.ErrorHandler(ex);
                return IntPtr.Zero;
            }
        }

        static string ChannelName;
        RemoteMon Interface;
        LocalHook CreateFileWHook;
        LocalHook CreateFileAHook;
        public void Main (RemoteHooking.IContext InContext, string InChannelName)
        {
            try
            {
                Interface = RemoteHooking.IpcConnectClient<RemoteMon>(InChannelName);
                ChannelName = InChannelName;
                Interface.IsInstalled(RemoteHooking.GetCurrentProcessId());
            }
            catch (Exception ex)
            {
                Interface.ErrorHandler(ex);
            }
            
        }
        public void Run(RemoteHooking.IContext InContext, string InChannelName)
        {
            try
            {
                CreateFileWHook = LocalHook.Create(LocalHook.GetProcAddress("Kernel32.dll", "CreateFileW"), new TCreateFileW(hkCreateFileW), this);
                CreateFileWHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
                CreateFileAHook = LocalHook.Create(LocalHook.GetProcAddress("Kernel32.dll", "CreateFileA"), new TCreateFileA(hkCreateFileA), this);
                CreateFileAHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
            }
            catch (Exception ex)
            {
                Interface.ErrorHandler(ex);
            }
            try
            {
                RemoteHooking.WakeUpProcess();
            }
            catch (Exception ex)
            {
                Interface.ErrorHandler(ex);
            }
            while (true)
            {
                Thread.Sleep(1000);
            }
        }
    }
}

**Comment by spazzarama** [comment]
You have renamed your class from Main to Class1 but not changed your constructor. Change public void Main to public Class1.
