### ISSUE TITLE
Add a new NuGet target for Visual Studio 2017

### ISSUE THREAD

**Issue by monamimani** [EasyHook/EasyHook#181]
When I try to compile in visual studio 2017 with the package from NuGet it can't find the libs because there is no folder v141 in the package folder.

**Comment by ethivierge** [comment]
Is it possible to push this live now or you need to wait for the 2.8 milestone?

**Comment by spazzarama** [comment]
This has now been released - see 2.7.6682.0

**Comment by ethivierge** [comment]
Thanks alot!
