### ISSUE TITLE
is it possible to update _WIN32_WINNT to a more up to date value?

### ISSUE THREAD

**Issue by monamimani** [EasyHook/EasyHook#185]
Is there a valid reason to do in easyhook.h this?
#define _WIN32_WINNT            0x500

It prevents the ability to call CheckRemoteDebuggerPresent because it needs 0x0501 or later.

see
https://msdn.microsoft.com/en-us/library/windows/desktop/ms679280(v=vs.85).aspx

Because I wanted to be able to debug the NativeInjectionEntryPoint function so I do

1. CreateProcess Suspended
2. do CheckRemoteDebuggerPresent while false
3. attach the debugger to the target app
4. call RhInjectLibrary

This way it is pretty convenient to do and I can break into the function.

To work around this define I had to have my include in a specific order.

**Comment by spazzarama** [comment]
Probably just need to have an ifndef around it.

So that solved your debugger issue changing the value?
