### ISSUE TITLE
how to use COMClassInfo with c++?

### ISSUE THREAD

**Issue by ice3366** [EasyHook/EasyHook#191]
I ran remote hook using EasyHook (hook Beep() in Tutorials )with C++ successful. 
Then I want to hook a com interface. But when i create a COMClassInfo object : COMClassInfo cci1 = new COMClassInfo(typeof(CLSID_DirectInputDevice8), typeof(IID_IDirectInputDevice8W), "GetCapabilities"); 
It failed : undeclared identifier COMClassInfo . I have already included "easyhook.h" 

environment： easyhook v2.7.6270.0 , vs2017 ,win10 64

**Comment by spazzarama** [comment]
COMClassInfo is only available in the managed library. If you want to use that you will need to implement within C#
