### ISSUE TITLE
How to get address of com interface method address with c++?

### ISSUE THREAD

**Issue by ice3366** [EasyHook/EasyHook#192]
I want to hook a com interface method. 
For example:  hook the method GetCapabilities() of DirectInputDevice8 object
I am using easyhook v2.7.6270.0  and vs2017 c++

How to get the address of the method?

**Comment by spazzarama** [comment]
EasyHook supports retrieving the address of COM methods in managed mode. See the code for [COMClassInfo](http://easyhook.github.io/api/html/T_EasyHook_COMClassInfo.htm) for more info. You could implement a similar approach natively.
