### ISSUE TITLE
Inject CreateProcess into child process (Unmanaged)

### ISSUE THREAD

**Issue by imtrobin** [EasyHook/EasyHook#207]
Hi, is it possible to hook CreateProcess in child process I created without another dll? I want to have my main app be notified when CreateProcess is called in my child process. Also, I read in old unmanaged docs there's are issues with 64bit/32bit hooking with unmanaged C++, is that still true?

**Comment by rjamesnw** [comment]
I'm interested in this as well - can I hook automatically into child processes? This would create a kind of file system sandbox of sorts.

**Comment by MarcusWichelmann** [comment]
Why don't you hook the CreateProcess (and related) Win32 Method so you can create a new hooked process based on the received method parameters yourself?

**Comment by spazzarama** [comment]
> is it possible to hook CreateProcess in child process I created without another dll
Do you mean you create a child process and then that process calls CreateProcess as well and you want to hook that? What you could do is RtlCreateSuspendedProcess into your child process, hook CreateProcess in the child process, then wake up the process with RhWakeUpProcess. If you aren't calling CreateProcess originally, then also hook CreateProcess in the host app as @MarcusWichelmann mentioned, then override the call with RtlCreateSuspendedProcess instead.

> I read in old unmanaged docs there's are issues with 64bit/32bit hooking with unmanaged C++, is that still true?
There is no automated WoW64 boundary handling when using the unmanaged library, you would have to create your own solution in this instance.
