### ISSUE TITLE
Hooking NtClose works on Windows 7 (x64) but crashes on Windows 10 (x64) version 1703

### ISSUE THREAD

**Issue by putertubbie** [EasyHook/EasyHook#211]
How to reproduce:
1. Download the "RemoteFileMonitor" example.
2. Add the following code:
```
        [DllImport("ntdll.dll", ExactSpelling = true, SetLastError = false)]
        static private extern int NtClose(IntPtr hObject);

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        delegate int NtClose_Delegate(IntPtr hObject);

        int NtClose_Hook(IntPtr hObject)
        {
            try
            {
                lock (_messageQueue)
                {
                    if (_messageQueue.Count < 1000)
                    {
                        // Add message to send to FileMonitor
                        _messageQueue.Enqueue(
                            string.Format("[{0}:{1}]: NtClose",
                            EasyHook.RemoteHooking.GetCurrentProcessId(), EasyHook.RemoteHooking.GetCurrentThreadId()));
                    }
                }
            }
            catch
            {
                // swallow exceptions so that any issues caused by this code do not crash target process
            }

            return NtClose(hObject);
        }

```
3. Add hook creation, activation and disposal calls among the other hooks:
```
            var ntCloseHook = EasyHook.LocalHook.Create(
                EasyHook.LocalHook.GetProcAddress("ntdll.dll", "NtClose"),
                new NtClose_Delegate(NtClose_Hook),
                this);
```
```
             ntCloseHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
```
```
             ntCloseHook.Dispose();
```

4. Build and run FileMonitor on Windows 7 injecting into "C:\windows\notepad.exe". Works like a charm!
5. Running the same binary as in (4) on Windows 10 causes an immediate crash. Rebuilding on Windows 10 does not change the behavior.

I have tried removing the messaging code from the hook, leaving only the call to the original NtClose function, but that does not change the behavior either.

I'm using Microsoft Visual Studio Community 2017, version 15.3.3 and the FileMonitor example is dated 2017-02-05.

Any clues?

**Comment by spazzarama** [comment]
What if you try CloseHandle instead?

Also try a localhook only version so you can test in a controlled environment to see if it works there or not.

**Comment by spazzarama** [comment]
Also try debugging the target and then inject and step through the code and handler.

**Comment by putertubbie** [comment]
Thanks for the reply!
Hooking CloseHandle works but I never got around to testing any of your other suggesions. As soon as I returned to my development computer it started updating and after installing version 1709 "Fall Creators Update" of Windows 10 the issue seems to be gone. If the issue reappears I'll dig into the reasons as you suggested.
