### ISSUE TITLE
EasyHook can't hook when a project uses Windows SDK 10

### ISSUE THREAD

**Issue by sasmaster** [EasyHook/EasyHook#212]
Hi!
I have been using this lib for a while for native C++ stuff.But my new C++ projects uses Windows SDK 10 and not 8.1  . The lib complains that it can't find NativeInjectionEntryPoint  . I first was sure that something wrong with my hook DLL,but tripple checked that I have NativeInjectionEntryPoint   declared.Then also verified that when switching to Win SDK 8,1 the lib works fine. This is a real blocker,as C++ developers have no choice but to migrate to Win SDK 10 because of the operating system. 
My dev env : 
Windows 10 64bit
VS 2015, C++ 64bit project.
Thanks.

**Comment by spazzarama** [comment]
@sasmaster can you check if the [native remote hooking tutorial](http://easyhook.github.io/tutorials/nativeremotehook.html) works?

**Comment by spazzarama** [comment]
@sasmaster I am still unable to reproduce this issue on Win 10 with the native remote hooking tutorial (re-targeted to Win10 SDK v10.0.17134.0 and v141 platform tools). Please reopen this issue with more details if you are still experiencing a problem.
