### ISSUE TITLE
CreateIoCompletionPort

### ISSUE THREAD

**Issue by abatar1** [EasyHook/EasyHook#213]
I want to hook [CreateIoCompletionPort ](https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa363862(v=vs.85).aspx) from known process. From code below I attempt to see on my console any message but nothing happends. What am I doing wrong?

        private static LocalHook _hook;

        [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
        private delegate IntPtr CreateIoCompletionPortDelegate(
            IntPtr FileHandle, 
            IntPtr ExistingCompletionPort,
            IntPtr CompletionKey, 
            uint NumberOfConcurrentThreads);

        private IntPtr CreateIoCompletionPort_Hook(
            IntPtr FileHandle,
            IntPtr ExistingCompletionPort,
            IntPtr CompletionKey,
            uint NumberOfConcurrentThreads)
        {
            Console.WriteLine("Api call hooked.")
        }
        public MapHook(int pId)
        {
            _hook = LocalHook.Create(
                LocalHook.GetProcAddress("kernel32.dll", "CreateIoCompletionPort"),
                new CreateIoCompletionPortDelegate(CreateIoCompletionPort_Hook),
                null);
            _hook.ThreadACL.SetInclusiveACL(new[] {pid});
        }

**Comment by spazzarama** [comment]
What value are you using in “pid”? This should be a thread id, and by using SetInclusiveACL you are saying “only hook these thread ids”.

**Comment by abatar1** [comment]
Pid is a Process.Id. Do I need to use Process.Threads instead?

**Comment by spazzarama** [comment]
LocalHook will create a hook within the current process only, if you want to hook within another process you need to inject an assembly, and then hook from that assembly using LocalHook (which will now be running in the target process).

Generally you will want to use SetExclusiveACL(new[] {0}); which excludes the current thread, and hooks all others (for the current process).
