### ISSUE TITLE
question/help about host/injected comunication

### ISSUE THREAD

**Issue by bymaximus** [EasyHook/EasyHook#215]
I want to know if possible if is possible to have the host creating the ipc server and injecting into target (normal process flow), but the target will also creates a a ipc server at entry point and will make a first 'ping' to the host with the created channel name and then the host will create a ipc client connection to this ipc server created at injected code.

I tried it but im getting host unable to find the pipe, I check and the pipe exists and have full write/read, any help?

**Comment by spazzarama** [comment]
Yes it is possible to setup bidirectional IPC. Take a look at spazzarama/Direct3DHook for an example (in the entry point constructor)

**Comment by bymaximus** [comment]
I tried that but got compile errors for ClientCaptureInterfaceEventProxy when assign the events to interface,
```
                _interface.Disconnected += _clientEventProxy.DisconnectedProxyHandler;
                _clientEventProxy.Disconnected += () =>
                {
                    // We can now signal the exit of the Run method
                    _runWait.Set();
                };
```

I will try again, update soon I can

**Comment by bymaximus** [comment]
WOW, just WOW, got it running now, not sure why, previous I got error while assigning the proxies events, anyway, thank you.

**Comment by spazzarama** [comment]
Glad it worked, it is a useful approach. 

Although not great if you need low-latency communications (look at my SharedMemory library for a lock-free circular buffer implementation).
