### ISSUE TITLE
Loading EasyHook.dll using Assembly.Load gives illegal path exception

### ISSUE THREAD

**Issue by matteke-games** [EasyHook/EasyHook#220]
Hi,

I subscribed to the AppDomain.CurrentDomain.AssemblyResolve event in case it couldnt find some dll. When I return EasyHook(loaded using a hardcoded byte array) I get an error saying I have an illegal path. It happens on this line: Path.Combine(Path.GetDirectoryName(typeof(Config).Assembly.Location), "EasyLoad32.dll"), (line 678 in RemoteHook.cs

Exact error message: 

 	mscorlib.dll!System.IO.Path.LegacyNormalizePath(string path, bool fullCheck, int maxPathLength, bool expandShortPaths)	Unknown	No symbols loaded.
 	mscorlib.dll!System.IO.Path.InternalGetDirectoryName(string path)	Unknown	No symbols loaded.
 	EasyHook!EasyHook.RemoteHooking.InjectEx(int InHostPID, int InTargetPID, int InWakeUpTID, int InNativeOptions, string InLibraryPath_x86, string InLibraryPath_x64, bool InCanBypassWOW64, bool InCanCreateService, bool InRequireStrongName, object[] InPassThruArgs)	Unknown	No symbols loaded.
 	EasyHook!EasyHook.RemoteHooking.Inject(int InTargetPID, string InLibraryPath_x86, string InLibraryPath_x64, object[] InPassThruArgs)	Unknown	No symbols loaded.

**Comment by spazzarama** [comment]
Remote injection is relying on the location of EasyHook.dll to find the EasyLoad*.dll. My guess is that because you are loading EasyHook from byte array the .Assembly.Location is not a valid path (the Config type referenced is in EasyHook assembly)

**Comment by matteke-games** [comment]
Aaah yes, what if we changed that function to Application.StartupPath, wouldnt that fix it?

**Comment by spazzarama** [comment]
Is there a reason you don’t have it loading EasyHook from a file location? Do you have EasyLoad*.dll in same spot?

If anything changes here I would probably prefer to just low the path to be specified/overridden rather than hardcoded. Currently it is assumed the EasyHook.dll and the supporting files are in the same directory.

**Comment by matteke-games** [comment]
Yes, I wanted to keep it small(1 file) so I embedded all requiring files as resources and extract them on program start, but since easyhook itself is .net I thought I could load it without needing it to touch the disk. Also isnt that why you added a todo there? To let a user specify the location and if the user didnt you could use the same method as now. I can make that change and then make a pull request?

**Comment by spazzarama** [comment]
Sure, be sure to target the develop branch.

**Comment by matteke-games** [comment]
Will do that

**Comment by matteke-games** [comment]
Closed #221
