### ISSUE TITLE
The given 64-Bit library does't exist!

### ISSUE THREAD

**Issue by JeffreyKenniston** [EasyHook/EasyHook#226]
`System.ArgumentException: 'STATUS_INVALID_PARAMETER_5: The given 64-Bit library does not exist! (Code: 2)'`

`string dll = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "NxtBot.dll");
            RemoteHooking.Inject(procs[0].Id, dll, dll, 0);'`

![untitled](https://user-images.githubusercontent.com/20978106/36339692-30bc0cde-1399-11e8-8b48-3ea7d3479c57.png)
`

**Comment by spazzarama** [comment]
Do you have EasyLoad32/64?

**Comment by Lalalaaaaaaa** [comment]
i got the same problem but i already have EasyLoad32/64.dll, however it still not works
![捕获1](https://user-images.githubusercontent.com/39038665/56334176-e8965d80-61c9-11e9-827a-76920df7f92d.PNG)
