### ISSUE TITLE
How can I hook the following threads?

### ISSUE THREAD

**Issue by 474172261** [EasyHook/EasyHook#227]
Hi,I have to add hooks for all following threads when program start,but I notice that the hooks installed are not enabled unless I called LhSetInclusiveACL.But this function can't add following threads id,I can't call this again when a new thread starting,is there any API can enable hooks for all threads ?

**Comment by 474172261** [comment]
And I wonder get the original ret addr to do something,how can I get that ? I notice that easyhook store it in a global list,but I can't find the global index of list.what't index's name?

**Comment by spazzarama** [comment]
Use LhSetExclusiveACL (I usually use with threadId of 0 == current thread), and any thread ID not provided will be interrupted.

> the original ret addr

Do you mean the original function address to bypass the hook? Or do you mean something else?

**Comment by 474172261** [comment]
Thanks for your replay : ) ,if so I have to create a new thread for hook to avoid exclusive current thread,emmm,not perfect enough.I have to hook CreateThread to add inclusive for each thread created ?

when calls of a hooked function,the instruction **call** will push the return address in stack,and easyhook changed it before call my hook function,after finishing my hook function,easyhook restore the original return address in stack.

I want to get this return address from stack in my hook function to note "where called this",because of easyhook's change,I can't get it from stack now.I notice that easyhook use the function **LhBarrierOutro** for restoring the real **RetAddress** and need two parameters.Seems CALL_NET_OUTRO (in Hookspecific_x64.asm )calls it finally.
It's hard to export these for me.Is there any easily way to get the real return address?

**Comment by spazzarama** [comment]
@474172261 - re the ACL, try using LhSetExclusiveACL and pass through a count of 0 (and empty array of thread ids) - from looking at the code, when using native hooks this should work fine.

Currently the return address is not available from within your hook handler.

**Comment by spazzarama** [comment]
Actually can you check if `LhBarrierGetReturnAddress` gives you the correct value?

**Comment by 474172261** [comment]
Yes,that's it.Thanks so much!
