### ISSUE TITLE
C# Assemblyresolve Load not working

### ISSUE THREAD

**Issue by 22092** [EasyHook/EasyHook#229]
After CurrentDomain_AssemblyResolve , I call EasyHook.RemoteHooking it will throw DllNotFoundException.

May I know how to load easyhook from embed resource?

 `
AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;`

private static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
              {

            Assembly assembly = Assembly.GetExecutingAssembly();

            using (var stream = assembly.GetManifestResourceStream("EasyHook.dll"))

            {

                byte[] buffer = new byte[stream.Length];

                stream.Read(buffer, 0, buffer.Length);

                stream.Flush();

                stream.Close();

                return Assembly.Load(buffer);

            }
}

**Comment by asmichi** [comment]
Let me jump in, but the answer is simple: you cannot. EasyHook*.dll must reside in a disk.

- `Assembly.Load` cannot load native DLLs. It is not for native DLLs. (Try that outside AssemblyResolve handlers and see an exception thrown.)
- Essentially EasyHook performs `LoadLibraryW(L"...EasyHook*.dll")` in the target process to load itself into the target process.

**Comment by asmichi** [comment]
>  `Assembly.Load` cannot load native DLLs. It is not for native DLLs. (Try that outside AssemblyResolve handlers and see an exception thrown.)

Ah, sorry, you are talking about the managed wrapper (EasyHook.dll)...

EasyHook.dll uses EasyHook32.dll and EasyHook64.dll (`essentially [DllImport("EasyHook32.dll",...)`), so you need to have these DLLs in the disk along with your exe.
