### ISSUE TITLE
Win API Hooks - Process stops working during detour call

### ISSUE THREAD

**Issue by duketwo** [EasyHook/EasyHook#242]
I'm detouring CryptDecrypt/CryptEncrypt of a game to inspect the packet flow / encrypted files. 
The problem I have is that the process just stops working if any extensive processing is being done within the detour method.
No crash, the execution just stops.

Im attaching the hooks, wake up the process. Then several thousand small zlib compressed files going through CryptEncrypt method. Just logging the size is fine. When trying to uncompress them the process just halts. It's not the decompression method itself, anything extensive will lead to the process halting.

Any hints how to debug that behaviour?

**Comment by spazzarama** [comment]
Ideally your hook is as simple as possible, queueing work for another if suitable. Can you confirm that just setting up a large loop will also halt? Could be that the caller is expecting a thread to complete within a timeout ? Not sure.

**Comment by duketwo** [comment]
Reduced the execution time by adding queues. No problems since then. Thank you.
