### ISSUE TITLE
Support far jumps even if they are not the first instruction

### ISSUE THREAD

**Issue by pheber** [EasyHook/EasyHook#243]
As 64 bit applications are becoming more prevalent, we increasingly face the issue of windows APIs which are unhookable (e.g. the OleIsCurrentClipboard method).

As discussed on https://gitter.im/EasyHook, it should be possible to extend EasyHook to support this. We would like to officially request that feature :).

If we can contribute or assist in development, please let us now (please note, however, that my assembler is "a bit" rusty to say the least).

**Comment by spazzarama** [comment]
@pheber I believe that this can work (in 64-bit mode), simply by replacing the existing [lines 394 & 395 of reloc.c](https://github.com/EasyHook/EasyHook/blob/master/DriverShared/LocalHook/reloc.c#L394) with:

```
#ifdef _M_X64
	if(pOld != InEntryPoint)
		THROW(STATUS_NOT_SUPPORTED, L"Hooking far jumps is only supported if they are the first instruction.");
#endif
```

Would you be able to make this change locally and test with your known use cases?

**Comment by spazzarama** [comment]
Just a heads up I had the conditional define incorrect, it should be `#ifndef _M_X64` not `#ifdef _M_X64`.

**Comment by Firedragonweb** [comment]
Tested it successfully with our use case - thank you!
