### ISSUE TITLE
how to fix "c++ completion routine has return success but didn't raise the remote event (code 0)" after Recompiling the source code?

### ISSUE THREAD

**Issue by micro-dever** [EasyHook/EasyHook#245]
When I recompile the source code, prompt the error 
"c++ completion routine has return success but didn't raise the remote event (code 0)" 
The use of the downloaded DLL does not have this problem .
How to modify the configuration to solve this problem? 
Os:win 10 
Vs:2013

**Comment by spazzarama** [comment]
Can you confirm if you are building using the batch file?

**Comment by micro-dever** [comment]
@spazzarama  YES.
i have downloaded all versions-source from github. All versions have this problem after compiling .
As long as the replacement of the download Binaries can be successful.
So, guess if there is a place to be configured .


Test app: example  /  FileMon.exe

**Comment by spazzarama** [comment]
@micro-dever I haven't built with VS2013 for a long time, only VS2015 and VS2017, that is the only thing I can think of without setting up a test environment.

Do you have a VS2017 build environment you can try with?

**Comment by micro-dever** [comment]
@spazzarama  I built with vs 2015  ,and got the same result.
the message is returned by EasyHookDll->thread.c

ps： where can i got the version code:2.7.4761.0  ?

**Comment by spazzarama** [comment]
@micro-dever EasyLoad uses the UnmanagedExport NuGet to create the native exports. Perhaps that is not working correctly for you.

**Comment by spazzarama** [comment]
@micro-dever can you confirm that when you build EasyLoad, you get the .exp and .lib files in addition to the .dll?

**Comment by micro-dever** [comment]
@spazzarama  YES 
i got EasyLoad32.lib/exp and  EasyLoad64.lib/exp , the four files

**Comment by spazzarama** [comment]
@micro-dever I'll take a look, can you please also check against the latest: https://github.com/EasyHook/EasyHook/archive/v2.7.6684.0.zip

**Comment by spazzarama** [comment]
@micro-dever I used the code you linked, ran build.bat, and then filemon.exe and then targeted C:\Windows\notepad.exe and it worked fine.

**Comment by micro-dever** [comment]
@spazzarama 
As expected 
because i ran build.bat from version 6684 and got the same result.

i found there is a file EasyHookTestCert.cer,  is this should be installed?
and  Is it possible to be related to the SNK file

**Comment by spazzarama** [comment]
@micro-dever no that .cer file is not used. EasyHook is built using AppVeyor. There must be something wrong with your environment. If you must build from code, perhaps setup a CI environment using AppVeyor instead.
