### ISSUE TITLE
Is it possible to hook a script execution on each process creation

### ISSUE THREAD

**Issue by chongchai** [EasyHook/EasyHook#248]
For example, I have a bat script like that:
```
a.exe xxx
b.exe xxx
echo 2 > 1.txt
```
How to hook the process creation of a.exe and b.exe? 
I read the document and sample but can't come up with a solution.

**Comment by spazzarama** [comment]
For this you would need to implement a driver and install a callback for process creation using [PsSetCreateProcessNotifyRoutine](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-pssetcreateprocessnotifyroutine).

**Comment by chongchai** [comment]
@spazzarama Thanks for your quickly reply.
Can you tell me more about:
If I also want to monitor file creation and access for each process in the bat script, can eazyhook be used to implement?

**Comment by spazzarama** [comment]
Let's assume you have a driver that is listening for new processes with PsSetCreateProcessNotifyRoutine or perhaps PsSetCreateThreadNotifyRoutine or LdrRegisterDllNotification (whatever best works for your situation and the lifecycle you want in the process).

Your kernel-mode code could then load your .dll into the target processes. This .dll would be user-mode code that uses EasyHook (or some other hooking mechanism) to install the hooks etc...

**Comment by chongchai** [comment]
@spazzarama Thank you very much for the detailed explanation
