### ISSUE TITLE
hook customized com failure

### ISSUE THREAD

**Issue by suncodeer** [EasyHook/EasyHook#255]
I create one COM with 2013 ATL.
It is remote hook. One customized activex is placed on the IE.
But it doesn't to come into my delegate method.
And I get correct Class ID &Interface ID.
[
	object,
	uuid(D78CF79C-D15C-42EA-85C2-882951F1A9EB),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICalc : IDispatch
library ATLToBeHookedV5Lib
{
	importlib("stdole2.tlb");
	[
		uuid(B31DFAAC-B524-40A1-A72A-0999FF394EFD),		
		control
	]
Then I initialize this com with easyhook.
EasyHook.COMClassInfo cci1 = new EasyHook.COMClassInfo(new Guid("B31DFAAC-B524-40A1-A72A-0999FF394EFD"), new Guid("D78CF79C-D15C-42EA-85C2-882951F1A9EB"), 3);
There is only one method in interface 
interface ICalc : IDispatch{
	[id(1)] HRESULT add2([in] LONG var1, [in] LONG var2, [out, retval] LONG* var3);
};
Then add hook method
            var addHook = EasyHook.LocalHook.Create(
                    cci1.MethodPointers[0],
                    new AddDelegate(AddHooked),
                    null
            );
        #region add2
        [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = false)]
        public delegate IntPtr AddDelegate(Int32 var1, Int32 var2, out IntPtr var3);

        private static IntPtr AddHooked(Int32 var1, Int32 var2, out IntPtr var3)
        {
            MessageBox(0, "Hello, PInvoke.NET", "PInvokeLab", 0);
            var3 = (System.IntPtr)var2;

            return var3;
        }
        #endregion
        #region recv

**Comment by suncodeer** [comment]
After Query Is Loaded.    cci1.IsModuleLoaded()).ToString() ==== True
Methods pointer address  8791465270850
I can get pointer address

**Comment by suncodeer** [comment]
var addHook = EasyHook.LocalHook.Create(
                    cci1.MethodPointers[0],
                    new AddDelegate(AddHooked),
                    null
            );
addHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
addHook.Dispose();
****
64bit dll 
EasyHook.RemoteHooking.Inject

dead loop has been executed and sleep(500)

**Comment by spazzarama** [comment]
Did you use Inject to inject your remote hook assembly into the target process?

**Comment by suncodeer** [comment]
It works well. One thing is strange. The order is five not three.
