### ISSUE TITLE
some issues about hook com failure

### ISSUE THREAD

**Issue by suncodeer** [EasyHook/EasyHook#257]
[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = false)]
        public delegate IntPtr AddDelegate(out IntPtr var3,Int32 var1, Int32 var2, );

        private static IntPtr AddHooked(out IntPtr var3,Int32 var1, Int32 var2, )
        {
            var3 = var1 + var2
            return var3;
        }

The parameter transfer will from right to left.
But when i use out keyword, the IE will crash down.
But when i remove keyword, the new caculation value could be transferred to the outside.
It means that in JS codes, only '0' will will be returned.

**Comment by suncodeer** [comment]
@spazzarama could you please help me?

**Comment by suncodeer** [comment]
when i use 
AddHooked ( IntPtr var3, Int32 var2, Int32 var1)
Marshal.StructureToPtr(199, var3, true);
The browser will crash.

**Comment by suncodeer** [comment]
@spazzarama Hopyfully I can get support from your side.

**Comment by spazzarama** [comment]
What is the original method signature?

**Comment by spazzarama** [comment]
Usually the first parameter is for “this”.

So try:

(IntPtr self, int var1, int var2, out int var3).

**Comment by suncodeer** [comment]
Thank you for your quickly and warmly reply.

******** com definition *******
interface ICalc : IDispatch{
[id(1)] HRESULT add2([in] LONG var1, [in] LONG var2, [out, retval] LONG* var3);
};

********* js codes *****
alert( Calc.add2(5,2) ) // no return value for this method

when I　test the method with below signature.
private static IntPtr AddHooked(out IntPtr var3,Int32 var1, Int32 var2, )

[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = false)]
public delegate IntPtr AddDelegate(out IntPtr var3,Int32 var1, Int32 var2, );

in the invoked method
var2 // value is 5
var1 // value is 2
It seems parameters will be transferred from right to left. ( a little strange, but in the doc you said we have to use convention 'stdcall' not 'decl')
When i change the address of var3, programs will crash.

************ with your new methods ***********
(IntPtr self, int var1, int var2, out int var3).
it means i can use codes below in the invoked method.
return self(var1,var2 out var3)
and Marshal.StructureToPtr(1999, var3, true);

**Comment by suncodeer** [comment]
sorry to forget to address you.
@spazzarama

**Comment by suncodeer** [comment]
I can set value for var3.
Thank your quickly and warmly reply.

**Comment by spazzarama** [comment]
Can you try ref int var3 instead of out int var3 @suncodeer

**Comment by suncodeer** [comment]
Hi Justin,
   My name is dongdong.
   Currently I can use out int var3 to change original value. It works well. Thank you for your big help and your amazing easyhook.
   New problem should be 
after hook com & Iexplorer.exe crash
   [Guid("D78CF79C-D15C-42EA-85C2-882951F1A9EB")]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface IID_Calc
{
    [PreserveSig]
    int add2(
        [In] Int32 var1,
        [In] Int32 var2,
        [Out] out Int32 var3
        ); // fourth method due to IUnknown methods QueryInterface, AddRef and Release
}

    [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = false)]
    public delegate int AddDelegate(IID_Calc self, Int32 var2, Int32 var1, out Int32 var5);

    public static int AddHooked(IID_Calc self, Int32 var1, Int32 var2, out Int32 var5)
    {
        var1 = var1 + 100;
        var2 = var1 + 200;
        return self.add2(var1, var2, out var5);
    }
   @spazzarama I have used self pointer to call add2 method. But IE will crash.

In the meantime I have tired methods below. Still crash
public static int AddHooked(IntPtr self, Int32 var1, Int32 var2, out Int32 var5)
{
var1 = var1 + 100;
var2 = var1 + 200;

        IID_Calc myCalc = GCHandle.FromIntPtr(self).Target as IID_Calc;

        return myCalc.add2(var1, var2, out var5);
        //return self.add2(var1, var2, out var5);
    }


Could you please help me ?

attach com interface signature
interface ICalc : IDispatch{
[id(1)] HRESULT add2([in] LONG var1, [in] LONG var2, [out, retval] LONG* var3);
};



In the meantime,
I want to use olydb64 to analyze the problem. But hooked method will be canceled. Actually I was a web developer.
I am very fresher guy in the C# area.
You should be very busy on some your own problems.
Can you please tell me how to anlayze the problem ? like debug or other tricky methods.
It is not good habit to ask you questions always. 


At 2018-08-30 04:53:52, "Justin Stenning" <notifications@github.com> wrote:


Can you try ref int var3 instead of out int var3 @suncodeer
