### ISSUE TITLE
How could I hook dispinterface  by using easyhook?

### ISSUE THREAD

**Issue by Dongdong13579** [EasyHook/EasyHook#261]
For example when I try to load (_IShockwaveFlashEvents )
EasyHook.COMClassInfo address = new EasyHook.COMClassInfo(new Guid("D27CDB6E-AE6D-11CF-96B8-444553540000"), new Guid("D27CDB6D-AE6D-11CF-96B8-444553540000"), 3);

flashEvent.Query();
flashEvent.IsModuleLoaded()  // after query It will be equal to "true"
But when I try to access address.MethodPointers[0] // but the value is zero.

**Comment by spazzarama** [comment]
Don’t forget that it will also have IUnknown methods, or possibly others too depending on what interfaces it inherits from. These methods will appear first.

**Comment by Dongdong13579** [comment]
@spazzarama Thank you for your reply.
EasyHook.COMClassInfo address = new EasyHook.COMClassInfo(new Guid("D27CDB6E-AE6D-11CF-96B8-444553540000"), new Guid("D27CDB6D-AE6D-11CF-96B8-444553540000"), 0);
I have changed the number into '0'.
Loaded is equal to 'True'. 
But address.MethodPointers[0] is still '0'

**Comment by spazzarama** [comment]
@Dongdong13579 I'm not a COM expert, but from what I can see I don't see any reason it wouldn't be supported. The issue I think will be finding the correct point in the life-cycle (and reference to instance) to hook them...

**Comment by Dongdong13579** [comment]
ok get your point. I will try to pay much more efforts on checking the life-cycle.
And thank you for your reply.
