### ISSUE TITLE
How to use EasyHook in kernel

### ISSUE THREAD

**Issue by muradkarakas** [EasyHook/EasyHook#264]
EasyHook is a great library but documentation is not enough. Additionally, its source code is not fully provided. So, I cannot know how it works.

I tried to use it in a kernel driver. I stuck even in the first line of code which is;

EasyHookQueryInterface function calls 
   NtStatus = IoGetDeviceObjectPointer(&DeviceName, FILE_READ_DATA, OutEasyHookDrv, &hEasyHookDrv);
   What is EasyHook device ? Why do I need it ? How can I install it ?

Regards

**Comment by spazzarama** [comment]
All source code is provided. What source could you not find?

**Comment by spazzarama** [comment]
Do you mean the Windows Auxiliary API library redistributables (Aux_lib)?

**Comment by spazzarama** [comment]
Someone has done a reverse engineer of that C lib here: https://github.com/David-Reguera-Garcia-Dreg/auxlib

No idea if it works as a drop in replacement or not.
