### ISSUE TITLE
Hook 2 different functions with a single dll injection?

### ISSUE THREAD

**Issue by Blade94** [EasyHook/EasyHook#266]
Hello! I'm trying to make a remote hook on CreateFileA function and fopen function, both from kernel32.dll.
My intent is to run the hooked CreateFileA to make my application write on an output file what is written on a configuration file opened by fopen function. The problem is that fopen in Windows calls internally CreateFileA, causing to open the output file (so the application reads from the output file and writes it on the output file itself).
I want to ask if it is possible to hook 2 functions in a single dll: what i would try to do is to uninstall CreateFileA hook after completion and install it back after fopen completion but to do so, fopen function needs the HOOK_TRACE_INFO of CreateFileA code, because I still need the injected code for CreateFileA after this operation.
I hope that my explanation is clear enough :)

Thanks in advance for the answers!

**Comment by spazzarama** [comment]
You could implement a flag (or interlocked or mutex,etc) that you set on entry into fopen hook and clear on exit so you revert to default behaviour within the CreateFileA hook rather than uninstalling/reinstalling.

**Comment by Blade94** [comment]
Thanks for the answer! But how can I set to the default behaviour with a flag? Sorry for the stupid question but I'm still learning this thing and I don't understand how to revert to default behavuoir without uninstalling/reinstalling.

**Comment by spazzarama** [comment]
Within your hook simply check the flag and if set, call the original method and return its result with no modifications to behaviour.

If the flag is not set then you continue to change the behaviour as you currently do.

**Comment by Blade94** [comment]
If I set the value of the flag as a global variable in one hook, will it be visible in the other? And will it keep its value?

**Comment by spazzarama** [comment]
That’s the idea, try it and see, I don’t know what your code bass looks like. If it doesn’t then you can look at semaphores or mutexs etc, lots of options - but these are unrelated to the hooks themselves so just google for it.
