### ISSUE TITLE
Calling the original COM function from the hook

### ISSUE THREAD

**Issue by IPaunescu** [EasyHook/EasyHook#267]
I need to hook a method of a COM class, I have the following:

1)	Delegate and hook callback:

private delegate void MyDelegate([In, MarshalAs(UnmanagedType.IUnknown)] object o, [In, MarshalAs(UnmanagedType.BStr)] string s);

void theHookMethod([In, MarshalAs(UnmanagedType.IUnknown)] object o, [In, MarshalAs(UnmanagedType.BStr)] string s)
{

 	// step 1 - do some work with the ‘s’ parameter – log it to file

	// step 2 - call the original xxx method, so the hooked application can continue undisturbed
}

2)	The targeted COM method is (as taken from OLE/COM object viewer):
void xxx([in] BSTR s);

3)	The hooking setup:

EasyHook.COMClassInfo cci = new EasyHook.COMClassInfo(new Guid("…"), new Guid("…"), 8);
cci.Query();
IntPtr hookedMethodAddress = cci.MethodPointers[0];
EasyHook.LocalHook hook = EasyHook.LocalHook.Create(hookedMethodAddress, new MyDelegate (theHookMethod), null);
hook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });

My hook method gets called successfully. 
All I need to do is to log the parameter – this works, and then call the original method so the hooked application can continue without noticing it was hooked. But this last step does not work, I don’t know how to do it. All examples I have found are about Win32 hooking and calling the original method from inside the hook. But I don’t know how to do it for COM.

I'm stuck with this for days, any help is appreciated.
Thank you!

**Comment by spazzarama** [comment]
It’s done the same as for Win32. Except of course your first parameter is always the com obj.

**Comment by IPaunescu** [comment]
Thank you for your reply. 
For Win32, in the example 'Creating a local hook' it is very clear how the original function is called. 
But for COM, I don't know which method address to use in the call. I tried like this:

originalFunctionPointer = (MyDelegate)
                Marshal.GetDelegateForFunctionPointer(X, typeof(MyDelegate));

For X, I tried to use cci.MethodPointers[0] and hook.HookBypassAddress.
But when I invoke the delegate 'originalFunctionPointer' in the hook function, I does not work.

Can you give me a hint on this?

Thank you!

**Comment by pschelling** [comment]
Hmm, I have kind of the same problem. a solution would be helpfull.

**Comment by spazzarama** [comment]
I would use IntPtr for o, rather than object.

There is no need to use the HookBypassAddress when from within the hook delegate, instead just call the original function (you can use the same function pointer you used to install the hook). EasyHook detects that the call is happening from within the hook handler and passes the call through without intercepting.

Here is a `Hook` helper class from the Direct3DHook example project that simplifies this process for you: [https://github.com/spazzarama/Direct3DHook/blob/master/Capture/Hook/Hook.cs](https://github.com/spazzarama/Direct3DHook/blob/master/Capture/Hook/Hook.cs).

The usage is like this:

```
// Delegate signature
[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
delegate int DXGISwapChain_PresentDelegate(IntPtr swapChainPtr, int syncInterval, SharpDX.DXGI.PresentFlags flags);

// Create hook
Hook<DXGISwapChain_PresentDelegate> DXGISwapChain_PresentHook = new Hook<DXGISwapChain_PresentDelegate>(
                addressOfPresent,
                new DXGISwapChain_PresentDelegate(PresentHook),
                this);
DXGISwapChain_PresentHook.Activate();

// hook handler:
int PresentHook(IntPtr swapChainPtr, int syncInterval, SharpDX.DXGI.PresentFlags flags)
{
    // 1. do stuff
    // 2. call original
    return DXGISwapChain_PresentHook.Original(swapChainPtr, syncInterval, flags);
}
```

See [DXHookD3D11.cs](https://github.com/spazzarama/Direct3DHook/blob/master/Capture/Hook/DXHookD3D11.cs) for more details.
