### ISSUE TITLE
How to call other original functions in native c++

### ISSUE THREAD

**Issue by leonluffy** [EasyHook/EasyHook#269]
I use A1 and B1 function to hook A and B function, now I want to call the original B function in A1 function, how can I do this?

**Comment by spazzarama** [comment]
Use LocalHook.BypassHookAddress (be careful that you don’t uninstall the hook while using that address)

**Comment by spazzarama** [comment]
The native equivalent is LhGetHookBypassAddress

**Comment by leonluffy** [comment]
>           The native equivalent is LhGetHookBypassAddress

Thank you
