### ISSUE TITLE
COM function hooking from native cpp

### ISSUE THREAD

**Issue by bsddemon** [EasyHook/EasyHook#271]
Hi,

Is it possible to hook a COM function in native CPP using EasyHook or should I switch to CS?

Thanks in advance
- Matty

**Comment by spazzarama** [comment]
Yes you can, you just have to determine the address to the method you want to hook (create an instance and then vtable lookup).

**Comment by bsddemon** [comment]
Hi Justin,

Thanks for the answer. I was hoping I could use the COMClassInfo method in native as well. Since it is not, I think I initially will go for a managed solution.

For this reason, as an experiment, I thought I could try to create a CS dll to inject in the "http://easyhook.github.io/tutorials/nativeremotehook.html" example. For native I the example works. However for my CS solution it returns:
"RhInjectLibrary failed with error code = -1073741582
Unable to find the required native entry point in the given 32-bit library."

I created the following code:
"namespace BeepHook
{
    public class InjectionEntryPoint : EasyHook.IEntryPoint
    {
        public InjectionEntryPoint(
            EasyHook.RemoteHooking.IContext context,
            string channelName)
        {
        }

        public void Run(
            EasyHook.RemoteHooking.IContext context,
            string channelName)
        {
            // Install hook
            var createFileHook = EasyHook.LocalHook.Create(
                EasyHook.LocalHook.GetProcAddress("kernel32.dll", "Beep"),
                new Beep_Delegate(Beep_Hook),
                this);

            // Activate hooks on all threads except the current thread
            createFileHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });

            // Wake up the process (required if using RemoteHooking.CreateAndInject)
            EasyHook.RemoteHooking.WakeUpProcess();
        }

        [DllImport("Kernel32.dll", SetLastError = true, CharSet = CharSet.Auto)]
        static extern uint GetFinalPathNameByHandle(IntPtr hFile, [MarshalAs(UnmanagedType.LPTStr)] StringBuilder lpszFilePath, uint cchFilePath, uint dwFlags);

        [UnmanagedFunctionPointer(CallingConvention.StdCall,
                    CharSet = CharSet.Unicode,
                    SetLastError = true)]
        delegate IntPtr Beep_Delegate(
            UInt32 dwFreq, UInt32 dwDuration);

        [DllImport("kernel32.dll",
            CharSet = CharSet.Unicode,
            SetLastError = true, CallingConvention = CallingConvention.StdCall)]
        static extern IntPtr Beep(
            UInt32 dwFreq, UInt32 dwDuration);

        IntPtr Beep_Hook(
           UInt32 dwFreq, UInt32 dwDuration)
        {
            // now call the original API...
            return Beep(dwFreq + 1000, dwDuration);
        }
    }
}"

What is wrong with this code?

**Comment by spazzarama** [comment]
@bsddemon the dllexport was if you wanted to create an entry point that could be called by a native remote inject + hook. But going with C# instead is working for you so don't worry about it.
