### ISSUE TITLE
Query COM interface fails

### ISSUE THREAD

**Issue by bsddemon** [EasyHook/EasyHook#272]
I try to hook a COM method which runs in a native assembly with a CS dll.

The COMView program rapports
IID	Text	ProxyStubClsid32
{6554ECA6-A8D6-4938-A82F-175FBADDAD70}	InterestingInterface	{A6C85003-15BE-470E-B159-8F20E4F1CE69}

CLSID	Text	Type	Type Value	ProgID	TypeLib
{A6C85003-15BE-470E-B159-8F20E4F1CE69}	PSFactoryBuffer	InProcServer32	C:\Program files (x86)\bla\AssembyOfInterest.dll		

From the IDL file I know I am interested in the second method, hence vtable position is 4.

My hook has the following code
                EasyHook.COMClassInfo cci = new EasyHook.COMClassInfo(
                    new Guid("A6C85003-15BE-470E-B159-8F20E4F1CE69"), 
                    new Guid("6554ECA6-A8D6-4938-A82F-175FBADDAD70"), 4);

                bool rVal = cci.Query();
                _server.ReportMessage(string.Format("[{0}:{1}]: cci.Query: {2}",
                    EasyHook.RemoteHooking.GetCurrentProcessId(), 
                    EasyHook.RemoteHooking.GetCurrentThreadId(), rVal));

I use the FileMonitor example to inject my DLL in the process and to check the rVal value.

I expected rVal to be true, but it returns false.

COMViewer gives for the executable
Key	Value	CLSID	Shell\Open\Command
InterestingService.InterestingService InterestingService Class	{F233B064-3BFA-4753-8FB1-1ABB53B9AABB}	

I also tried 
                EasyHook.COMClassInfo cci = new EasyHook.COMClassInfo(
                    new Guid("F233B064-3BFA-4753-8FB1-1ABB53B9AABB"), 
                    new Guid("6554ECA6-A8D6-4938-A82F-175FBADDAD70"), 4);

This also returns false.

What could be the next step(s) to try?

**Comment by bsddemon** [comment]
I have done some more experiments. First I tried to inject the DLL on the "server" side of the interface, now I tried on the "client" side. With the same result.

On the client side, the MIDL compiler generates the following file
MIDL_DEFINE_GUID(IID, IID_IService,0xC78F40C2,0x501D,0x410e,0xB7,0x47,0x31,0x26,0x2C,0x66,0xE8,0x31);

... many other IIDs ...

MIDL_DEFINE_GUID(IID, IID_InterestingInterface ,0x6554ECA6,0xA8D6,0x4938,0xA8,0x2F,0x17,0x5F,0xBA,0xDD,0xAD,0x70);

... many other IIDs ...

MIDL_DEFINE_GUID(CLSID, CLSID_CoService,0xF233B064,0x3BFA,0x4753,0x8F,0xB1,0x1A,0xBB,0x53,0xB9,0xAA,0xBB);

And uses the following code for cocreation
    HRESULT hr = CoCreateInstance( CLSID_CoService,
                    NULL,
                    ( ULONG )CLSCTX_ALL,
                    IID_IService,
                    ( void** ) &m_pIService ) ;

**Comment by bsddemon** [comment]
I am a step further

With sysinternals I see that the hook dll tries to access the following location in the registry
HKCU\Software\Classes\WOW6432Node\CLSID\{f233b064-3bfa-4753-8fb1-1abb53b9aabb}\InprocServer32

In the registry I found this equivalent
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{F233B064-3BFA-4753-8FB1-1ABB53B9AABB}\LocalServer32

Only here I see LocalServer32 i.s.o InprocServer32.

I guess this is the case because I have to run the software as administrator.

Is there a way to change the search path of EasyHook?

**Comment by spazzarama** [comment]
@bsddemon that is currently hard coded in [COMClassInfo.cs line 281](https://github.com/EasyHook/EasyHook/blob/master/EasyHook/COMClassInfo.cs#L281)

**Comment by spazzarama** [comment]
@bsddemon try creating a modified version of COMClassInfo in your app with the path changes and see if that works for you.

**Comment by spazzarama** [comment]
@bsddemon did you try this and did it work?

**Comment by bsddemon** [comment]
I could not get the archive compiling. So in the end I it tried with native and got it working

**Comment by spazzarama** [comment]
Ok great thanks
