### ISSUE TITLE
A long jump error

### ISSUE THREAD

**Issue by michaelgorman** [EasyHook/EasyHook#279]
Not sure what to make of this, also I don't know why it doesnt fall into the catch block and just crashes the whole app. https://imgur.com/a/9d7aAka 
This works 99% of the time, the server object is the ServerInterface

**Comment by spazzarama** [comment]
Have you tried queuing the info and sending to the IPC outside of the hook? Similar to orocessmon example.

**Comment by michaelgorman** [comment]
I have not, let me take a look

**Comment by michaelgorman** [comment]
After review I'm not sure this will fix my problem. I'm inside the InjectionEntryPoint object which inherits from IEntryPoint. the server object is instantiated from IpcConnectClient, which is processmon is on the otherside of the fence. I feel like if I implement this all I would be doing is moving the problem out of textouthook callback and moving the problem to the timer fire, no? Or am I missing something?

**Comment by spazzarama** [comment]
By moving it outside of the hook handler we can rule out any interference. Basically if it still happens it is a problem with the IPC only, and you will be able to focus on that.

**Comment by michaelgorman** [comment]
I moved the code and the same crash still occurs in the callback, so i guess it's got nothing to do with the server. This time it died on the Monitor.Enter. If is it stuck waiting or taking too long then I suppose the OS will drop the hook, right? The ProcessTextOutQueue method below is run on a sep thread


`      
      [UnmanagedFunctionPointer(CallingConvention.StdCall, SetLastError = true)]
      delegate bool TextOutADelegate(IntPtr hdc, int x, int y, String lpString, int length);

      [DllImport("gdi32.dll", CharSet = CharSet.Ansi, EntryPoint = "TextOutA", SetLastError = true, CallingConvention = CallingConvention.StdCall)]
      private static extern bool TextOutA(IntPtr hdc, int x, int y, String lpString, int length);

      private bool TextOutAHook(IntPtr hdc, int x, int y, String lpString, int length)
      {
         Boolean lockTaken = false;
         try
         {
            if (length > 0 && _captureTextMonitorEnabled == ServerInterface.CaptureTextMonitorStatuses.Running)
            {
               String text = lpString.Substring(0, length);
               IntPtr hwnd = WindowFromDC(hdc);
               Int32 xOffset = 0, yOffset = 0;
               RECT clip; SIZE size;

               GetTextExtentPoint32(hdc, lpString, length, out size);
               GetWindowOffsets(hwnd, ref xOffset, ref yOffset);
               GetClipBox(hdc, out clip);

               clip.Top += yOffset;
               clip.Left += xOffset;
               clip.Bottom += yOffset;
               clip.Right += xOffset;

               Rectangle clipBox = new Rectangle(clip.Left, clip.Top, clip.Right - clip.Left, clip.Bottom - clip.Top);
               Rectangle textRect = new Rectangle(x + xOffset, y + yOffset, size.X, size.Y);
               textRect = GetTextRectangle(hdc, textRect, clipBox);
               Monitor.Enter(_textOutQueue, ref lockTaken);               
               _textOutQueue.Enqueue(new GDIText { Value = text, Rectangle = textRect, ClipBox = clipBox });   
                           
               //if (length < 0)
               //{
               //   DrawScreenRect.DrawRect(hwnd, clipBox.Left, clipBox.Top, clipBox.Right - clipBox.Left, clipBox.Bottom - clipBox.Top, Color.LimeGreen);
               //   DrawScreenRect.DrawRect(hwnd, textRect.Left, textRect.Top, textRect.Right - textRect.Left, textRect.Bottom - textRect.Top, Color.Magenta);
               //}
               //Debug.WriteLine(text);
            }
         }
         catch(Exception ex)
         {
            Console.WriteLine(ex.ToString());
         }
         finally
         {
            if(lockTaken) Monitor.Exit(_textOutQueue);
         }
         return TextOutA(hdc, x, y, lpString, length);
      }

      public void Run(EasyHook.RemoteHooking.IContext context, string channelName)
      {
         // Injection is now complete and the server interface is connected
         _server.Installed(EasyHook.RemoteHooking.GetCurrentProcessId());

         //var textOutWHook = EasyHook.LocalHook.Create(EasyHook.LocalHook.GetProcAddress("gdi32.dll", "TextOutW"), new TextOutWDelegate(TextOutWHook), null);
         var textOutAHook = EasyHook.LocalHook.Create(EasyHook.LocalHook.GetProcAddress("gdi32.dll", "TextOutA"), new TextOutADelegate(TextOutAHook), null);

         // Activate hooks on all threads except the current thread
         textOutAHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });


        //rest of function is not included
     }

      private void ProcessTextOutQueue()
      {
         while (_captureTextMonitorEnabled == ServerInterface.CaptureTextMonitorStatuses.Running)
         {
            if (Monitor.TryEnter(_textOutQueue))
            {
               try
               {
                  if (_textOutQueue.Count > 0)
                  {
                     GDIText text = _textOutQueue.Dequeue();
                     _server.Add(text.Value, text.Rectangle, text.ClipBox);
                  }
               }
               finally
               {
                  Monitor.Exit(_textOutQueue);
               }
            }            
         }
      }
`

**Comment by michaelgorman** [comment]
OH i see a problem with ProcessTextOutQueue the server.add is within the lock. let me refractor and see if I still have the problem

**Comment by spazzarama** [comment]
@michaelgorman did that fix your issue?

**Comment by michaelgorman** [comment]
yeah i think so, we can close this  thx!
