### ISSUE TITLE
How to hook a class member function?

### ISSUE THREAD

**Issue by elliott-wen** [EasyHook/EasyHook#280]
I know one possible way is to get the address from the vtable? But could anyone enlighten me with some source codes?

**Comment by spazzarama** [comment]
For C# here is an example `GetVtblAddresses`: https://github.com/spazzarama/Direct3DHook/blob/master/Capture/Hook/BaseDXHook.cs#L123

```csharp
        protected IntPtr[] GetVTblAddresses(IntPtr pointer, int numberOfMethods)
        {
            return GetVTblAddresses(pointer, 0, numberOfMethods);
        }

        protected IntPtr[] GetVTblAddresses(IntPtr pointer, int startIndex, int numberOfMethods)
        {
            List<IntPtr> vtblAddresses = new List<IntPtr>();

            IntPtr vTable = Marshal.ReadIntPtr(pointer);
            for (int i = startIndex; i < startIndex + numberOfMethods; i++)
                vtblAddresses.Add(Marshal.ReadIntPtr(vTable, i * IntPtr.Size)); // using IntPtr.Size allows us to support both 32 and 64-bit processes

            return vtblAddresses.ToArray();
        }
```

**Comment by elliott-wen** [comment]
Here is a C++ example to hook the Draw function in DirectWrite
``auto hDWriteCreateFactory = static_cast<LPVOID>(GetProcAddress(hDwriteMod, "DWriteCreateFactory"));

	if (hDWriteCreateFactory == nullptr)
	{
		std::cerr << ("Couldn't get handle to hDWriteCreateFactory\n");
		return;
	}
	
	IDWriteFactory* pDWriteFactory_ = nullptr;

	auto hr = static_cast<HRESULT(WINAPI *)(
		DWRITE_FACTORY_TYPE,
		REFIID,
		IUnknown ** ppFactory)>(hDWriteCreateFactory)(
			DWRITE_FACTORY_TYPE_SHARED,
			__uuidof(IDWriteFactory),
			reinterpret_cast<IUnknown **>(&pDWriteFactory_));

	if (FAILED(hr))
	{
		std::cerr << ("Couldn't get create dwrite factory\n");
		return;
	}

	//Initial a textlayout and textformat
	const wchar_t* wszText_ = L"Hello World using  DirectWrite!";
	UINT32 cTextLength_ = (UINT32) wcslen(wszText_);
	IDWriteTextFormat *pTextFormat = nullptr;
	IDWriteTextLayout *pTextLayout = nullptr;

	hr = pDWriteFactory_->CreateTextFormat(L"Gabriola", NULL, DWRITE_FONT_WEIGHT_REGULAR, DWRITE_FONT_STYLE_NORMAL, DWRITE_FONT_STRETCH_NORMAL, 72.0f, L"en-us", (&pTextFormat));
	if (FAILED(hr))
	{
		std::cerr << ("Couldn't get create text format\n");
		return;
	}



	hr = pDWriteFactory_->CreateTextLayout(
		wszText_,      // The string to be laid out and formatted.
		cTextLength_,  // The length of the string.
		pTextFormat,  // The text format to apply to the string (contains font information, etc).
		100.0,         // The width of the layout box.
		10.0,        // The height of the layout box.
		&pTextLayout  // The IDWriteTextLayout interface pointer.
	);
	
	if (FAILED(hr))
	{
		std::cerr << ("Couldn't get create text layout\n");
		return;
	}

	
	dWriteTextLayoutVtable = reinterpret_cast<void **>(*reinterpret_cast<void **>(pTextLayout));
	originalTextLayoutDraw = static_cast<HRESULT(*)(void *self, void *context, IDWriteTextRenderer* render, FLOAT x, FLOAT y)>
		(dWriteTextLayoutVtable[DWRITETEXTLAYOUTDRAWMETHODSLOT]);
	

	// Perform hooking
	HOOK_TRACE_INFO hHook = { NULL }; // keep track of our hook

	NTSTATUS result = LhInstallHook(
		originalTextLayoutDraw,
		myDraw,
		NULL,
		&hHook);

**Comment by KMint1819** [comment]
@elliott-wen Hi, what's "DWRITETEXTLAYOUTDRAWMETHODSLOT" in the code?
