### ISSUE TITLE
Multiple Hooks

### ISSUE THREAD

**Issue by elliott-wen** [EasyHook/EasyHook#281]
Considering I am gonna hook two functions a & b.
Do I need two independent HOOK_TRACE_INFO variables like the following?

``
HOOK_TRACE_INFO hHooka = { NULL }; // keep track of our hook

NTSTATUS result = LhInstallHook(
		originalA,
		newA,
		NULL,
		&hHooka);

HOOK_TRACE_INFO hHookb = { NULL }; // keep track of our hook

result = LhInstallHook(
		originalB,
		newB,
		NULL,
		&hHookb);

**Comment by spazzarama** [comment]
Yes you should, you will need those references if you want to disable or uninstall the hooks.
