### ISSUE TITLE
Easyhook dispose the hook automatically,why?

### ISSUE THREAD

**Issue by KuoKongQingYun** [EasyHook/EasyHook#284]
After calling LocalHook.Create,I check the memory of the target function，its first opcode was replaced with a "jmp" opcode.
After calling  RemoteHooking.WakeUpProcess , the progress ran,but I check that function again,the "jmp" opcode  was restored with origin opcode, so the hooking became invalid,why?
I use CheatEngine to debug the progress,I found that the “jmp" opcode was restored by NativeAPI.LhWaitForPendingRemovals,but I didn't call any dispose or release function.

**Comment by spazzarama** [comment]
Did you keep a reference to the LocalHook? If the GC collects it then it will be disposed.

**Comment by KuoKongQingYun** [comment]
> Did you keep a reference to the LocalHook? If the GC collects it then it will be disposed.

Oh! As you say, I added an endless loop at the end of  the Run method, it works!
Thank you!
