### ISSUE TITLE
LhSetExclusiveACL doesn't work correctly

### ISSUE THREAD

**Issue by ZeinabMaghsoodi** [EasyHook/EasyHook#285]
I am gonna hook CreateFileW, WriteFile,...etc. 
This is part of dll for hook:
"CreateFileW" hook function is like this:

HANDLE HookCreateFile(parameters ...){
ofstream backupFile;
backupFile.open(...);
backupFile<<"test";
backupFile.close();
...
}

and for installation I have 
HOOK_TRACE_INFO hHookCreateFile = { NULL }; 
HOOK_TRACE_INFO hHookWriteFile = { NULL }; 

NTSTATUS result1 = LhInstallHook(
originalCreateFileW,
HookCreateFile,
NULL,
&hHookCreateFile );

NTSTATUS result2 = LhInstallHook(
originalWriteFile,
HookWriteFile,
NULL,
&hHookWriteFile );

ULONG ACLEntries[1] = {0};

LhSetExclusiveACL(ACLEntries,1,hHookCreateFile );
LhSetExclusiveACL(ACLEntries,1,hHookWriteFile );

and in my injector program I inject this dll as: 

RhInjectLibrary(MyConsoleAppID, 0, EASYHOOK_INJECT_DEFAULT, NULL, MyDllPath, NULL, 0);

but in my console program that just call createfileW and Writefile,  I found that in HookcreatefileW and line "backupFile<<"test";" HookWritefile called again. I expected that just createfileW and Writefile of my console program hook.
Where did i make mistakes?

**Comment by spazzarama** [comment]
With that code you are saying: "Hook all threads except for current thread"

Does that match what you are doing?

**Comment by ZeinabMaghsoodi** [comment]
> 
> 
> With that code you are saying: "Hook all threads except for current thread"
> 
> Does that match what you want to be doing?
> 
> Perhaps output the thread Id when you install hook, and also in your console app where you are expecting the hooks to be skipped. If you are using RhInjectLibrary I would expect the thread ids to be different.

Suppose I have B and A programs, that B is injector as previously I said, and A is injected. So I just want that A be injected. But the result of this program is in the way that B  injects A and also inject itself.
I can't find what's the problem.

**Comment by spazzarama** [comment]
Take a look at the remote hooking tutorial it shows you how to setup your remote entry point.

**Comment by ZeinabMaghsoodi** [comment]
> 
> 
> Take a look at the remote hooking tutorial it shows you how to setup your remote entry point.

I read the tutorial "https://easyhook.github.io/tutorials/nativeremotehook.html" completely and the written program is totally based on the tutorial.
There are several hooks, for example Writefile, CreatefileW, GetFileSize, GetFullPathNameW,...etc, and in each hook there is instructions to log specific messages. Each hook do well individually, but when I want to hook them all together the program will crash and a loop of calls will happen. for example in HookGetFileSize there is instructions (in injector dll):
myFile.open(...);  --> expected main CreateFileW call but HookCreateFileW called.
myFile<<"text";  --> expected main WreateFile call but HookWriteFile called.

But I don't want the injector injects itself.

**Comment by spazzarama** [comment]
@ZeinabMaghsoodi you could either exclude the thread where you call myFile.open, or manage some other state so you can skip any customised logic in your handlers and call the original.

**Comment by ZeinabMaghsoodi** [comment]
@spazzarama how I can exclude the thread when myFile.open() is call? I couldn't find anything.

**Comment by spazzarama** [comment]
@ZeinabMaghsoodi add the thread that is calling myFile.open to the exclusion list when you setup the ACL.

**Comment by spazzarama** [comment]
@ZeinabMaghsoodi if you need to sync your logic between multiple hooks, you need to maintain some state and use that to determine if behaviour should be changed.

OR - you can use the bypass address of your openfile hook using LhGetHookBypassAddress

**Comment by ZeinabMaghsoodi** [comment]
@spazzarama what is the second parameter of LhGetHookBypassAddress? I can't find any example.

**Comment by spazzarama** [comment]
@ZeinabMaghsoodi address of a pointer that will receive the address to use to bypass the hook.

**Comment by ZeinabMaghsoodi** [comment]
@spazzarama  Thanks :) My problem solved.
