### ISSUE TITLE
NuGet Package doesn't work with PackageReference blocks

### ISSUE THREAD

**Issue by qdot** [EasyHook/EasyHook#293]
In VS2019, PackageReference is now the default for keeping nuget references, versus the old and now unmaintained package.config. When using PackageReference with Easyhook, the EasyHook executables and DLLs don't seem to be added to the project correctly, and aren't copied to the compiled project on build.

**Comment by spazzarama** [comment]
thanks for the heads-up @qdot - I'll check out how best to refactor the packages (also for the native package) once I get around to installing VS2019 (might be a little while as flat out).

**Comment by qdot** [comment]
Just in case anyone else runs into this before it's fixed, here's an SO link that talks about how to go back from PackageReference to packages.config project format without having to rebuild your project from scratch:

https://stackoverflow.com/questions/45962998/switch-back-to-packages-config

Ended up working fine for me, and once I converted back to packages.config, EasyHook loaded up correctly.
