### ISSUE TITLE
error of Build project of easyhook 

### ISSUE THREAD

**Issue by forest123** [EasyHook/EasyHook#3]
Build project of easyhook and see lots of wrong messages
for example,definition error(such as int64,int32,...)

**Comment by forest123** [comment]
Build System driver(32 bit with Debug mode)

**Comment by spazzarama** [comment]
Which project exactly are you building? Are you using the build.bat?

If the driver project - this hasn't been updated for a while - needs quite a bit of work.

**Comment by forest123** [comment]
Thanks!
