### ISSUE TITLE
How to build EasyHook32Svc.exe and EasyHook64Svc.exe from the source code?

### ISSUE THREAD

**Issue by wpfpro** [EasyHook/EasyHook#30]
The only project seems to be used to build those exe files is EasyHookSvc.proj
But when building it the output is just the EasyHookSvc.exe

Are those exe files are pre-built from some other source code? If I can build them with the source code downloaded from here, how could I do that? Thank you very much.

**Comment by spazzarama** [comment]
They should get built fine with the build.bat

**Comment by wpfpro** [comment]
In fact what I have is the source code of the EasyHook 2.6 and there is not any build.bat file. I've also downloaded the EasyHook 2.7 but looks like it requires Visual Studio 2013 to build (I'm still using Windows 7 so still stick to VS 2012).

**Comment by spazzarama** [comment]
You can change the tools version in the project files to compile with VS2012

**Comment by wpfpro** [comment]
thank you for the info.
