### ISSUE TITLE
Taking input in the injector and passing it to the hook library

### ISSUE THREAD

**Issue by JillCrungus** [EasyHook/EasyHook#302]
For the project I'm working on I'd like to be able to take input in my injector console (in the form of typing in commands) and pass that input into the hook library.

I've seen a couple of issues about bidirectional IPC but they both just point to Direct3DHook library. This unfortunately doesn't help me because D3DHook is a large library with many components and it's incredibly difficult to untangle it and figure out what I need from it.

Any help would be appreciated, thanks.

**Comment by spazzarama** [comment]
Hi Jill, take a look at this stackoverflow answer, it may help you work through the code you need.

https://stackoverflow.com/a/44448309/323899
