### ISSUE TITLE
Kernel Mode hooking from easyhook

### ISSUE THREAD

**Issue by abdullahtoqeer523** [EasyHook/EasyHook#303]
How can we use easyhook for kernel mode drivers? forget about the patchguard, I just want to hook some functions in kernel mode. Can you please help?

**Comment by spazzarama** [comment]
You need to have the WDK installed and build EasyHookSys.sln

Unfortunately I don't have time to support using EasyHook in kernel mode.

**Comment by u-riaz** [comment]
@spazzarama do we have any tutorials for kernel hooks (supposing PG/KPP is already disabled) like the ones we've here (https://easyhook.github.io/tutorials.html) for user-mode hooks.
If no, any plans to write them, please.

**Comment by spazzarama** [comment]
There aren’t any kernel mode tutorials. I don’t have plans to write any myself due to time constraints.

If someone else has the time to contribute then that would be great. Any tutorial would need to cover dev environment setup and debugging config too.
