### ISSUE TITLE
How to Hook a .net program

### ISSUE THREAD

**Issue by ohacn** [EasyHook/EasyHook#305]
hi,
How to hook a .net(managed code) dll or exe?
I want to hook .net class method.
Help me,Thanks!

**Comment by spazzarama** [comment]
EasyHook doesn’t support hooking into managed methods currently.

Here is a library that does https://github.com/pardeike/Harmony

**Comment by brandonros** [comment]
How do you get reference to the parent process that you are being injected into, in order to do reflection and get the assemblies/methods/types you want to patch with Harmony?

When you inject with EasyHook, you can't access the assemblies of the parent managed process
