### ISSUE TITLE
Embedding EasyHook in a C# Class Library

### ISSUE THREAD

**Issue by VirtualSmile** [EasyHook/EasyHook#322]
Hey guys!

I'm only planning to use EasyHook for Local Hooking (using EasyHook locally after manual injection of my class library / .dll). Is it possible to embed only the necessary libraries / dll into my own class library? I'd just prefer to have it packaged into one .DLL.

I'm fairly inexperienced. Something similar to static linking in C / C++. I've used Costura Fody and ILMerge before but I'm not sure if they work in this case. 

Thanks!

**Comment by spazzarama** [comment]
For the managed code, yes. But you would still need the native .dll(s)
