### ISSUE TITLE
IpcCreateServer and multiple user sessions

### ISSUE THREAD

**Issue by michaelgorman** [EasyHook/EasyHook#323]
It looks like the default behavior according to the help is that 1 server is created and "authenticated users will be allowed to access the server" is this correct? I'm running on a windows server OS and will have multiple users. I noticed that each time the IpcCreateServer is called a unique channel name is returned so I'm not sure. I need to have 1 server per user session

**Comment by spazzarama** [comment]
@michaelgorman you can provide your own channel/channel name instead.

**Comment by michaelgorman** [comment]
Closing issue, they are indeed separate processes. My problem was a threading issue and race conditions
