### ISSUE TITLE
Unable to inject into 32bit process

### ISSUE THREAD

**Issue by michaelgorman** [EasyHook/EasyHook#338]
Update: I copied all the files to the dir as my app and now I get a different error:
Exception thrown: 'System.ApplicationException' in EasyHook.dll
Additional information: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)

Works fine for when my target is a 64 bit process but throws an error for the 32 bit process "The system cannot find the file specified"
my injectionLibrary dll was originally compiled as anycpu, I even tried compiling it specifically as x86 and same problem. My process is 64bit and not anycpu, the target process is 32bit. 

             RemoteHooking.Inject(
               processId, // ID of process to inject into
               @"D:\builds\blast\git\master.A\BLASTDriverTest\build\BLAST.Injection.X86.dll", // 32-bit library to inject (if target is 32-bit)
               injectionLibrary, // 64-bit library to inject (if target is 64-bit)
               channelName); // the parameters to pass into injected library

the dlls in the path 
D:\builds\blast\git\master.A\bin\EasyHook>dir /b
ComplexParameterInject.dll
ComplexParameterTest.exe
EasyHook.dll
easyhook.h
EasyHook32.dll
EasyHook32.lib
EasyHook32Svc.exe
EasyHook64.dll
EasyHook64.lib
EasyHook64Svc.exe
EasyHookTestCert.cer
EasyLoad32.dll
EasyLoad64.dll
FileMon.exe
FileMonInject.dll
ProcessMonitor.exe
ProcMonInject.dll
README.md
TestFuncHooks.exe

**Comment by Mobles** [comment]
Having the same issue, added the libs to my VC++ Directories and Link/Input/Additional Dependencies so I have no clue.

Getting EasyHook32.dll dependency can't be found with my Injector

**Comment by Mobles** [comment]
Fix that worked for me: Place the 32 bit Binary ( EasyHook32.dll ) with the injector :)

**Comment by michaelgorman** [comment]
So your app is 64 bit and you were able to get it to work?

**Comment by michaelgorman** [comment]
@Mobles I was able to get it working by setting the config path. I keep all the easyhook dlls in a separate dir underneath my assemblies. The 32 bit code is slightly diff from the 64 bit in easy hook and uses a different path to load the EasyHook32Svc.exe, the one below

EasyHook.Config.DependencyPath = Path.Combine(Path.GetDirectoryName(injectionLibrary), "EasyHook");
