### ISSUE TITLE
Easyhool.DLL does not compile

### ISSUE THREAD

**Issue by albgen** [EasyHook/EasyHook#342]
hi, 

i get the following issues

Severity	Code	Description	Project	File	Line	Suppression State
Error	RC1015	cannot open include file 'afxres.h'.	EasyHookDll	C:\Users\user\source\repos\EasyHook\EasyHookDll\EasyHookDll_64.rc	10	
Error	LNK1181	cannot open input file 'C:\Users\user\source\repos\EasyHook\Build\netfx3.5-Release\x64\EasyHook64.lib'	UnmanagedHook	C:\Users\user\source\repos\EasyHook\Examples\UnmanagedHook\LINK	1

**Comment by spazzarama** [comment]
You need to install MFC support from Visual Studio installer

**Comment by albgen** [comment]
Thanks
