### ISSUE TITLE
Injected DLL on another AppDomain

### ISSUE THREAD

**Issue by albgen** [EasyHook/EasyHook#344]
hi,

Really easy to use this library and many thanks, but i have a problem.  

My scenario is the following: 2 C# executable files. First one, let's say A is the target, Second one B, is the injector.
The purpose is to inject the dll from B to A and start some code which will get/list all assemblies of the main AppDomain in process A. 
The real purpose is actually to patch those assemblies with another library but this is another story.

The problem is that after injecting the dll, the A process has 2 AppDomains. The first one is the original one and the second one is the one of the injected Dll.

The question is: how do i get the assemblies of the first AppDomain in A?

thank you

**Comment by spazzarama** [comment]
@albgen EasyHook isn't designed to inject/hook into managed assemblies. You might like to look at [Harmony](https://github.com/pardeike/Harmony)

**Comment by michaelgorman** [comment]
I had to change the code in Loader.cs otherwise my gui interactions would not work

        public static int Load([MarshalAs(UnmanagedType.LPWStr)]String inParam)
        {
            try
            {
                lock (_lock)
                {
                    try
                    {
                        _injectCount++;
                       _easyHookDomain = AppDomain.CurrentDomain;

**Comment by albgen** [comment]
> @albgen EasyHook isn't designed to inject/hook into managed assemblies. You might like to look at [Harmony](https://github.com/pardeike/Harmony)

ehm Harmony is the patcher and needs a loader like EasyHook...

**Comment by albgen** [comment]
> @albgen I had to change the code in Loader.cs otherwise my gui interactions would not work
> 
> ```
>     public static int Load([MarshalAs(UnmanagedType.LPWStr)]String inParam)
>     {
>         try
>         {
>             lock (_lock)
>             {
>                 try
>                 {
>                     _injectCount++;
>                    _easyHookDomain = AppDomain.CurrentDomain;
> ```

Do you think chaning that --->>>  _easyHookDomain = AppDomain.CurrentDomain; might work?

**Comment by spazzarama** [comment]
Give it a try, probably it will. The creation of AppDomain was just to support assembly unloading.

**Comment by towserchen** [comment]
the same case.
I use Harmony to patch managed methods. but Harmony doesn't support inject dll so I utilize Easyhook to inject the process.
unexpectedly, Injection and patching is success but the patch method doesn't work.
