### ISSUE TITLE
Hooking failed with Error code 487: STATUS_NOT_SUPPORTED: Hooking jumps into the hooked entry point is not supported.

### ISSUE THREAD

**Issue by meza2003** [EasyHook/EasyHook#352]
Hooking failed with Error code 487: STATUS_NOT_SUPPORTED: Hooking jumps into the hooked entry point is not supported.

in source code noted "is not really unhookable but not worth the effort..."
how can i resolve this problem. it is vital for me.
please help me

**Comment by spazzarama** [comment]
It probably needs to maintain a chain of dependent hooks and require uninstalling them in specific order. You could try uncommenting the constraint and see how it behaves, but be sure to release the hooks in reverse order.

**Comment by meza2003** [comment]
can explain more please,
i have hooked a procedure by ordinal number and don't know about internal call chain.

**Comment by meza2003** [comment]
does Comment this Constraint?

if((AbsAddr >= (LONGLONG)InEntryPoint) && (AbsAddr < (LONGLONG)InEntryPoint + InEPSize))
/* is not really unhookable but not worth the effort... */
THROW(STATUS_NOT_SUPPORTED, L"Hooking jumps into the hooked entry point is not supported.");

**Comment by meza2003** [comment]
there is no permanent solution?

**Comment by spazzarama** [comment]
Not sure if commenting out that is enough but can try for your situation.

I don’t have time to implement a solution, but if someone else wants to they are welcome.

Perhaps you could outline your use case in a little more detail?

**Comment by meza2003** [comment]
i what to hook this :  Ordinal 4356

.text:000000018042263C ; =============== S U B R O U T I N E 
=======================================
.text:000000018042263C
.text:000000018042263C
.text:000000018042263C                 public MSO_4356
.text:000000018042263C MSO_4356        proc near               ; CODE XREF: sub_180421EF8+291↑p
.text:000000018042263C                                         ; sub_180421EF8+3D4↑p ...
.text:000000018042263C                 jmp     short loc_180422640
.text:000000018042263C ; ---------------------------------------------------------------------------
.text:000000018042263E                 align 20h
.text:0000000180422640
.text:0000000180422640 loc_180422640:                          ; CODE XREF: MSO_4356↑j
.text:0000000180422640                 jmp     short sub_180422644
.text:0000000180422640 MSO_4356        endp
.text:0000000180422640
.text:0000000180422640 ; ---------------------------------------------------------------------------
.text:0000000180422642                 align 4
.text:0000000180422644
.text:0000000180422644 ; =============== S U B R O U T I N E =======================================
.text:0000000180422644
.text:0000000180422644
.text:0000000180422644 sub_180422644   proc near               ; CODE XREF: MSO_4356:loc_180422640↑j
.text:0000000180422644                                         ; DATA XREF: .pdata:00000001815CAB84↓o
.text:0000000180422644
.text:0000000180422644 arg_0           = qword ptr  8
.text:0000000180422644
.text:0000000180422644                 mov     [rsp+arg_0], rbx
.text:0000000180422649                 push    rdi
.text:000000018042264A                 sub     rsp, 20h
.text:000000018042264E                 movsxd  rbx, ecx
.text:0000000180422651                 mov     rdi, rdx
.text:0000000180422654                 mov     ecx, ebx
.text:0000000180422656                 call    sub_180420DC0
.text:000000018042265B                 test    eax, eax
.text:000000018042265D                 js      short loc_180422681
.text:000000018042265F                 mov     rdx, rdi
.text:0000000180422662                 mov     ecx, ebx
.text:0000000180422664                 call    sub_1804224D0
.text:0000000180422669                 test    eax, eax
.text:000000018042266B                 js      short loc_180422681
.text:000000018042266D                 lea     rcx, qword_18159EC20
.text:0000000180422674                 mov     rdx, rdi
.text:0000000180422677                 mov     rcx, [rcx+rbx*8]
.text:000000018042267B                 mov     rax, [rcx]
.text:000000018042267E                 call    qword ptr [rax+10h]
.text:0000000180422681
.text:0000000180422681 loc_180422681:                          ; CODE XREF: sub_180422644+19↑j
.text:0000000180422681                                         ; sub_180422644+27↑j
.text:0000000180422681                 mov     rbx, [rsp+28h+arg_0]
.text:0000000180422686                 add     rsp, 20h
.text:000000018042268A                 pop     rdi
.text:000000018042268B                 retn
.text:000000018042268B sub_180422644   endp
.text:000000018042268B
.text:000000018042268C

**Comment by spazzarama** [comment]
Yeah ok, it is different to what I thought, it requires modifying the subsequent JMP instruction to work within the relocated location.

**Comment by meza2003** [comment]
What should i do? :))

**Comment by spazzarama** [comment]
I would try hooking later in the function / next function, it doesn’t look like it would be a problem to do that

**Comment by meza2003** [comment]
When do you think it will be ready?
I'm sorry, I wouldn't have bothered if my work wasn't urgent.

**Comment by spazzarama** [comment]
Did you try my suggestion of booking later in the target function? I’m not going to be working in this in the near future at all.

**Comment by meza2003** [comment]
What do you mean by "hooking later in the target function"?
target function jump into a sub that was not exported.
can explain your suggestion by c# code?
i don't have any knowledge about assembly language.

**Comment by meza2003** [comment]
does Comment the Constraint solve my problem in this case?

**Comment by spazzarama** [comment]
Take the address of target function and offset to sub

**Comment by meza2003** [comment]
hi
i can get address by Localhook.getprocAddress
then 
 LocalHook.Create(
                        GetProcAddress(MSO_Path, new IntPtr(OrdinalNum)+Offset),
                        new ConvertDateLocalToGreg_Delegate(MyConvertDateLocalToGreg), This);
is this correct? 
if true then how calculate offset?

**Comment by meza2003** [comment]
can explain with assembly code that i send in previous comments, thanks

**Comment by spazzarama** [comment]
You could memory scan forward looking for instruction or hard code offset based on the disassembly. 

Target address from your ASM 000000018042263C

Possible suitable location:
0000000180422644 (sub routine)

Offset to use is 0x0000000180422644 - 0x 000000018042263C

**Comment by meza2003** [comment]
OK, thank you very very much.
You helped a lot.

**Comment by meza2003** [comment]
Hi spazzarama,
I tested your suggestion and successfully hook target function.
Thank you.
