### ISSUE TITLE
how to run an client object method from server by ipc?

### ISSUE THREAD

**Issue by meza2003** [EasyHook/EasyHook#358]
I inject a dll into another process, i what to control injected dll from injector program? Can access object of injected dll on target process (as client) from injector program (as server)?

**Comment by BryceBarbara** [comment]
Yes, EasyHook provides some quick IPC functionality via the `EasyHook.RemoteHooking.IpcConnectClient` class. You can see it in use in [this tutorial](http://easyhook.github.io/tutorials/remotefilemonitor.html#serverinterface).

**Comment by spazzarama** [comment]
You can also setup bi-directional IPC using remoting as shown in https://github.com/spazzarama/Direct3DHook otherwise you can use any other IPC mechanism of your choice.
