### ISSUE TITLE
How to hook invoke of com IDispatch method

### ISSUE THREAD

**Issue by luckywuhan** [EasyHook/EasyHook#360]
How to hook invoke of com IDispatch method

**Comment by spazzarama** [comment]
Take a look at COMClassInfo: http://easyhook.github.io/api/html/T_EasyHook_COMClassInfo.htm

That class helps you get the address of the functions from COM class. Remember the hook handler first param will be point to the com obj (this/self).

```
// 1. Use imported Class and Interface Types
COMClassInfo cci1 = new COMClassInfo(typeof(CLSID_DirectInputDevice8), typeof(IID_IDirectInputDevice8W), "GetCapabilities");
// 2. Use Guid from class and interface types
COMClassInfo cci2 = new COMClassInfo(typeof(CLSID_DirectInputDevice8).GUID, typeof(IID_IDirectInputDevice8W).GUID, 3);
// 3. Use class and interface Guids directly (no need to have class and interface types defined)
COMClassInfo cci3 = new COMClassInfo(new Guid("25E609E5-B259-11CF-BFC7-444553540000"), new Guid("54D41081-DC15-4833-A41B-748F73A38179"), 3);

// Will output False if dinput8.dll is not already loaded
Console.WriteLine(cci1.IsModuleLoaded());
cci1.Query();
cci2.Query();
cci3.Query();
// Will output True as dinput8.dll will be loaded by .Query() if not already
Console.WriteLine(cci1.IsModuleLoaded());

// Output the function pointers we queried
Console.WriteLine(cci1.FunctionPointers[0]);
Console.WriteLine(cci2.FunctionPointers[0]);
Console.WriteLine(cci3.FunctionPointers[0]);

...

[ComVisible(true)]
[Guid("25E609E5-B259-11CF-BFC7-444553540000")]
public class CLSID_DirectInputDevice8
{
}

[ComVisible(true)]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("54D41081-DC15-4833-A41B-748F73A38179")]
public interface IID_IDirectInputDevice8W
{
    /*** IDirectInputDevice8W methods ***/
    int GetCapabilities(IntPtr deviceCaps); // fourth method due to IUnknown methods QueryInterface, AddRef and Release
    // other methods...
}
```

**Comment by luckywuhan** [comment]
@spazzarama 
### i want to log all com interface invoke，so hook com invoke method is my best choice.

### this is my code， but hook function not called.
### please help me

delegate IntPtr QueryInterfaceDelegate(IntPtr riid, ref IntPtr ppvObj);

        static IntPtr QueryInterfaceHook(IntPtr riid, ref IntPtr ppvObj)
        {
            MessageBox.Show("hooked");
            return IntPtr.Zero;
        }

        private void HookDemo()
        {
            try
            {
                string clsid = "73E4740C-08EB-4133-896B-8D0A7C9EE3CD";
                string iid = "133A76A3-A847-4613-BB39-8BE887ADADE6";
                var cci = new EasyHook.COMClassInfo(new Guid(clsid), new Guid(iid), 0);
                cci.Query();
                bool isloaded = cci.IsModuleLoaded();
                IntPtr methodPointer = cci.MethodPointers[0];//QueryInterface - 0 AddRef - 1 Release - 2
                var hook = EasyHook.LocalHook.Create(
                            cci.MethodPointers[0],
                            new QueryInterfaceDelegate(QueryInterfaceHook),
                            null
                            );
                hook.ThreadACL.SetExclusiveACL(new int[] { 0 });
                // call com interface
                safeEdit1.setRandom("1b54a680978c86e5867c");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }


### and this is com idl

// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: InputControl.dll

[
  uuid(2BA10EF5-8A81-4C57-92D6-591515ECF910),
  version(1.0),
  helpstring("InputControl 1.0 Type Library"),
  custom(DE77BA64-517C-11D1-A2DA-0000F8773CE9, 117441012),
  custom(DE77BA63-517C-11D1-A2DA-0000F8773CE9, 1559128955),
  custom(DE77BA65-517C-11D1-A2DA-0000F8773CE9, "Created by MIDL version 7.00.0500 at Wed May 29 19:22:34 2019
")

]
library INPUTCONTROLLib
{
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    dispinterface _IAxInputControlEvents;
    interface IAxInputControl;

    [
      uuid(2EA6AC75-6982-4A23-8B03-7B3CA3FDA647),
      helpstring("_IAxInputControlEvents Interface")
    ]
    dispinterface _IAxInputControlEvents {
        properties:
        methods:
            [id(0x00000001), helpstring("method OnFocus2")]
            HRESULT OnFocus2();
            [id(0x00000002), helpstring("method OnBlur2")]
            HRESULT OnBlur2();
    };

    [
      uuid(73E4740C-08EB-4133-896B-8D0A7C9EE3CD),
      helpstring("AxInputControl Class")
    ]
    coclass AxInputControl {
        [default] interface IAxInputControl;
        [default, source] dispinterface _IAxInputControlEvents;
    };

    [
      odl,
      uuid(133A76A3-A847-4613-BB39-8BE887ADADE6),
      helpstring("IAxInputControl Interface"),
      dual,
      oleautomation
    ]
    interface IAxInputControl : IDispatch {
        [id(0x00000002), propget, helpstring("property minLength")]
        HRESULT minLength([out, retval] long* pVal);
        [id(0x00000002), propput, helpstring("property minLength")]
        HRESULT minLength([in] long pVal);
        [id(0x00000003), propget, helpstring("property maxLength")]
        HRESULT maxLength([out, retval] long* pVal);
        [id(0x00000003), propput, helpstring("property maxLength")]
        HRESULT maxLength([in] long pVal);
        [id(0x00000004), propget, helpstring("property rule")]
        HRESULT rule([out, retval] BSTR* pVal);
        [id(0x00000004), propput, helpstring("property rule")]
        HRESULT rule([in] BSTR pVal);
        [id(0x00000005), propget, helpstring("property keyName")]
        HRESULT keyName([out, retval] BSTR* pVal);
        [id(0x00000005), propput, helpstring("property keyName")]
        HRESULT keyName([in] BSTR pVal);
        [id(0x00000006), helpstring("method clear")]
        HRESULT clear();
        [id(0x00000007), helpstring("method getLength")]
        HRESULT getLength([out, retval] long* pRet);
        [id(0x00000008), helpstring("method isValid")]
        HRESULT isValid([out, retval] long* pRet);
        [id(0x00000009), helpstring("method compareWith")]
        HRESULT compareWith(
                        [in] BSTR in, 
                        [out, retval] long* pRet);
        [id(0x0000000a), helpstring("method isEqual")]
        HRESULT isEqual(
                        [in] IUnknown* pOther, 
                        [out, retval] long* pRet);
        [id(0x0000000c), helpstring("method AddKeyPart")]
        HRESULT AddKeyPart(
                        BSTR keyPart, 
                        [out, retval] long* pRet);
        [id(0x0000000d), propput, helpstring("property UniqueID")]
        HRESULT UniqueID([in] BSTR rhs);
        [id(0x0000000f), helpstring("method commit")]
        HRESULT commit(
                        [in] IUnknown* pSubmit, 
                        [out, retval] long* pRet);
        [id(0x00000010), propput, helpstring("property isPassword")]
        HRESULT isPassword([in] long rhs);
        [id(0x00000011), helpstring("method commitKeyPart")]
        HRESULT commitKeyPart(
                        [in] IUnknown* pInputControl, 
                        [out, retval] long* pRet);
        [id(0x00000012), helpstring("method CapsOnOrNot")]
        HRESULT CapsOnOrNot([out, retval] long* pRet);
        [id(0x00000013), helpstring("method FocusOrNot")]
        HRESULT FocusOrNot([out, retval] long* pRet);
        [id(0x00000014), propget, helpstring("property CryptAlg")]
        HRESULT CryptAlg([out, retval] long* pVal);
        [id(0x00000014), propput, helpstring("property CryptAlg")]
        HRESULT CryptAlg([in] long pVal);
        [id(0x00000015), helpstring("method updateSeed")]
        HRESULT updateSeed([in] BSTR seed);
        [id(0x00000016), helpstring("method getValue")]
        HRESULT getValue([out, retval] BSTR* info);
        [id(0x00000017), helpstring("method setRules")]
        HRESULT setRules(
                        [in] BSTR m_bstrSetRules, 
                        [out, retval] long* m_lRet);
        [id(0x00000018), helpstring("method setChangeRules")]
        HRESULT setChangeRules(
                        [in] BSTR m_bstrChangeRules, 
                        [out, retval] long* m_lRet);
        [id(0x00000019)]
        HRESULT put_IP([in] BSTR IP);
        [id(0x0000001a)]
        HRESULT put_IP2([in] BSTR IP2);
        [id(0x0000001b)]
        HRESULT put_IP3([in] BSTR IP3);
        [id(0x0000001c)]
        HRESULT put_MAC([in] BSTR MAC);
        [id(0x0000001d)]
        HRESULT put_MAC2([in] BSTR MAC2);
        [id(0x0000001e)]
        HRESULT put_MAC3([in] BSTR MAC3);
        [id(0x0000001f)]
        HRESULT GetLastError([out, retval] BSTR* iError);
        [id(0x00000020), propget, helpstring("property ruleName")]
        HRESULT ruleName([out, retval] BSTR* pVal);
        [id(0x00000020), propput, helpstring("property ruleName")]
        HRESULT ruleName([in] BSTR pVal);
        [id(0x00000021), propget, helpstring("property changeRuleName")]
        HRESULT changeRuleName([out, retval] BSTR* pVal);
        [id(0x00000021), propput, helpstring("property changeRuleName")]
        HRESULT changeRuleName([in] BSTR pVal);
        [id(0x00000022), propput, helpstring("property IsBorderVisible")]
        HRESULT IsBorderVisible([in] VARIANT_BOOL rhs);
        [id(0x00000024), propput, helpstring("property BackgroundColor")]
        HRESULT BackgroundColor([in] BSTR rhs);
        [id(0x00000025), propput, helpstring("property PromptText")]
        HRESULT PromptText([in] BSTR rhs);
        [id(0x00000026), propput, helpstring("property PromptTextColor")]
        HRESULT PromptTextColor([in] BSTR rhs);
        [id(0x00000027), helpstring("method GetVersion")]
        HRESULT GetVersion([out, retval] BSTR* version);
        [id(0x00000028), helpstring("method SetCryptAlg")]
        HRESULT SetCryptAlg([in] long newVal);
        [id(0x00000029), helpstring("method SetIsPassword")]
        HRESULT SetIsPassword(long newVal);
        [id(0x0000002a), helpstring("method SetUniqueID")]
        HRESULT SetUniqueID([in] BSTR newVal);
        [id(0x0000002b), helpstring("method SetChangeRuleName")]
        HRESULT SetChangeRuleName(BSTR newVal);
        [id(0x0000002c), helpstring("method SetRuleName")]
        HRESULT SetRuleName([in] BSTR newVal);
        [id(0x0000002d), helpstring("method SetRule")]
        HRESULT SetRule([in] BSTR newVal);
        [id(0x0000002e), helpstring("method SetPromptTextColor")]
        HRESULT SetPromptTextColor([in] BSTR newVal);
        [id(0x0000002f), helpstring("method SetMinLength")]
        HRESULT SetMinLength([in] long newVal);
        [id(0x00000030), helpstring("method SetMaxLength")]
        HRESULT SetMaxLength([in] long newVal);
        [id(0x00000031), helpstring("method SetkeyName")]
        HRESULT SetkeyName([in] BSTR newVal);
        [id(0x00000032), helpstring("method SetIsBorderVisible")]
        HRESULT SetIsBorderVisible([in] VARIANT_BOOL newVal);
        [id(0x00000033), helpstring("方法SetBackgroundColor")]
        HRESULT SetBackgroundColor(BSTR newVal);
        [id(0x00000034), helpstring("method setRandom")]
        HRESULT setRandom([in] BSTR sRandomId);
        [id(0x00000035), helpstring("method setPublicKeyNew")]
        HRESULT setPublicKeyNew(
                        [in] BSTR sPublicKey, 
                        [out, retval] long* retValue);
        [id(0x00000036), helpstring("method getHwInfo")]
        HRESULT getHwInfo([out, retval] BSTR* hardwareInfo);
        [id(0x00000037)]
        HRESULT put_IPv6([in] BSTR IP);
        [id(0x00000038)]
        HRESULT put_IPv62([in] BSTR IP2);
        [id(0x00000039)]
        HRESULT put_IPv63([in] BSTR IP3);
        [id(0x0000003a)]
        HRESULT setIPType([in] long newVal);
    };
};

**Comment by spazzarama** [comment]
Your thread ACL setup is wrong for this example.

You are saying hook all threads except current.

Try int[]{} instead, or use SetInclusiveACL for this particular test

**Comment by luckywuhan** [comment]
> I think your thread ACL setup is wrong for this example.
> 
> You are saying hook all threads except current.
> 
> Try int[]{} instead, or use SetInclusiveACL for this particular test

Yes, you are right. it works.

Now i can hook QueryInterface interface, but i try to **hook invoke interface**，it failed.

How can i determine the index corresponds to the order method names ?

**Comment by spazzarama** [comment]
IDispatch inherits from IUnknown, so the first method of IDispatch has a zero-based index of 3 (4th method).

The order of the method members is as defined in the IDispatch interface.
