### ISSUE TITLE
fatal error LNK1104: cannot open file 'EasyHook32.lib'

### ISSUE THREAD

**Issue by ORCA666** [EasyHook/EasyHook#363]
my code :

         #include <string>

        #include <iostream>

        #include <Windows.h>

        #include <easyhook.h>      
        #if _WIN64
        #pragma comment(lib, "EasyHook64.lib")
        #else
        #pragma comment(lib, "EasyHook32.lib")
        #endif  
     using namespace std;
     BOOL WINAPI myBeepHook(DWORD dwFreq, DWORD dwDuration);
     BOOL WINAPI myBeepHook(DWORD dwFreq, DWORD dwDuration)
     {
     cout << "\n****All your beeps belong to us!\n\n";
     return Beep(dwFreq + 800, dwDuration);
       }
           int _tmain(int argc, CHAR* argv[])
            {
             HOOK_TRACE_INFO hHook = { NULL }; // keep track of our hook
           cout << "\n";
            cout << GetProcAddress(GetModuleHandle(TEXT("kernel32")), "Beep");
         // Install the hook
        NTSTATUS result = LhInstallHook(
        GetProcAddress(GetModuleHandle(TEXT("kernel32")), "Beep"),
        myBeepHook,
        NULL,
        &hHook);
        if (FAILED(result))
        {
        wstring s(RtlGetLastErrorString());
        wcout << "Failed to install hook: ";
        wcout << s;
        cout << "\n\nPress any key to exit.";
        cin.get();
        return -1;
        }
        cout << "Beep after hook installed but not enabled.\n";
        Beep(500, 500);  
      cout << "Activating hook for current thread only.\n";
       // If the threadId in the ACL is set to 0, 
       // then internally EasyHook uses GetCurrentThreadId()
      ULONG ACLEntries[1] = { 0 };
      LhSetInclusiveACL(ACLEntries, 1, &hHook);
     cout << "Beep after hook enabled.\n";
     Beep(500, 500);
     cout << "Uninstall hook\n";
     LhUninstallHook(&hHook);
     cout << "Beep after hook uninstalled\n";
     Beep(500, 500);
     cout << "\n\nRestore ALL entry points of pending removals issued by LhUninstallHook()\n";
     LhWaitForPendingRemovals(); 
     cout << "Press any key to exit.";
     cin.get();
      return 0;
      }

so i dont know what to do , the error is keep popping, although i download nuget & easy hook on visual studio 2019. can anyone help me !

**Comment by TENX-S** [comment]
Same problem here

**Comment by michaelgorman** [comment]
@alexa872  @TENX-S 

For the 32bit the dependencypath needs to be set but it isnt necessary for the 64bit, it's fine to have it set for both. I run both 32 & 64bit with this code

 


            String channelName = null;
            IpcServerChannel channel = RemoteHooking.IpcCreateServer<ServerInterface>(ref channelName, WellKnownObjectMode.Singleton);
            String injectionLibrary = Assembly.GetExecutingAssembly().Location;

            //
            //DEBUGGING!!!!!READ ME!!!!
            //inject will not load if it is already loaded from a diff dir, restart olf
            //
            Config.DependencyPath = Path.Combine(Path.GetDirectoryName(injectionLibrary), "EasyHook");
            RemoteHooking.Inject(
               processId, // ID of process to inject into
               injectionLibrary, // 32-bit library to inject (if target is 32-bit)
               injectionLibrary, // 64-bit library to inject (if target is 64-bit)
               channelName); // the parameters to pass into injected library

            ServerInterface server = RemoteHooking.IpcConnectClient<ServerInterface>(channelName);

**Comment by ORCA666** [comment]
> @alexa872 @TENX-S
> 
> For the 32bit the dependencypath needs to be set but it isnt necessary for the 64bit, it's fine to have it set for both. I run both 32 & 64bit with this code
> 
> ```
>         String channelName = null;
>         IpcServerChannel channel = RemoteHooking.IpcCreateServer<ServerInterface>(ref channelName, WellKnownObjectMode.Singleton);
>         String injectionLibrary = Assembly.GetExecutingAssembly().Location;
> 
>         //
>         //DEBUGGING!!!!!READ ME!!!!
>         //inject will not load if it is already loaded from a diff dir, restart olf
>         //
>         Config.DependencyPath = Path.Combine(Path.GetDirectoryName(injectionLibrary), "EasyHook");
>         RemoteHooking.Inject(
>            processId, // ID of process to inject into
>            injectionLibrary, // 32-bit library to inject (if target is 32-bit)
>            injectionLibrary, // 64-bit library to inject (if target is 64-bit)
>            channelName); // the parameters to pass into injected library
> 
>         ServerInterface server = RemoteHooking.IpcConnectClient<ServerInterface>(channelName);
> ```

Thanks man, although im late !!!! Like a lot late , but I didn't forgot, anyways thanks again for your share, I used another hooking library , there was a bug in linking an external lib file in vs 2019, thats why I kept getting this error, (the bug is patched now), but thank you
