### ISSUE TITLE
Hooking `CreateProcess` will never call back.

### ISSUE THREAD

**Issue by Meigs2** [EasyHook/EasyHook#372]
I'm currently unable to detect when `CreateProcess` is called. Installing a hook to `CreateProcess` and then calling the function using the exact same signature does not call the intercepted function. 

This issue seems to have been resolved in #290 but the user did not specify if/how this issue was resolved.

I have a feeling that I'm missing something very obvious however I do not know what else could be the issue. Other hooks work fine.

Here is a simple demo. Create a sample app and replace the Program.cs with the following (after installing EasyHook):

```csharp
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace TestLauncherApp
{
    class Program
    {
        [StructLayout(LayoutKind.Sequential)]
        internal struct STARTUPINFO
        {
            uint cb;
            IntPtr lpReserved;
            IntPtr lpDesktop;
            IntPtr lpTitle;
            uint dwX;
            uint dwY;
            uint dwXSize;
            uint dwYSize;
            uint dwXCountChars;
            uint dwYCountChars;
            uint dwFillAttributes;
            uint dwFlags;
            ushort wShowWindow;
            ushort cbReserved;
            IntPtr lpReserved2;
            IntPtr hStdInput;
            IntPtr hStdOutput;
            IntPtr hStdErr;
        }

        [StructLayout(LayoutKind.Sequential)]
        internal struct PROCESS_INFORMATION
        {
            public IntPtr hProcess;
            public IntPtr hThread;
            public int dwProcessId;
            public int dwThreadId;
        }

        [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Auto, CallingConvention = CallingConvention.StdCall)]
        private static extern bool CreateProcess(IntPtr lpApplicationName, string lpCommandLine, IntPtr lpProcAttribs, IntPtr lpThreadAttribs, bool bInheritHandles, uint dwCreateFlags, IntPtr lpEnvironment, IntPtr lpCurrentDir, [In] ref STARTUPINFO lpStartinfo, out PROCESS_INFORMATION lpProcInformation);

        [UnmanagedFunctionPointer(CallingConvention.StdCall, SetLastError = true)]
        delegate bool CreateProcess_Delegate(IntPtr lpApplicationName, string lpCommandLine, IntPtr lpProcAttribs, IntPtr lpThreadAttribs, bool bInheritHandles, uint dwCreateFlags, IntPtr lpEnvironment, IntPtr lpCurrentDir, [In] ref STARTUPINFO lpStartinfo, out PROCESS_INFORMATION lpProcInformation);

        bool CreateProcess_Hook(IntPtr lpApplicationName, string lpCommandLine, IntPtr lpProcAttribs, IntPtr lpThreadAttribs, bool bInheritHandles, uint dwCreateFlags, IntPtr lpEnvironment, IntPtr lpCurrentDir, [In] ref STARTUPINFO lpStartinfo, out PROCESS_INFORMATION lpProcInformation)
        {
            bool result = false;

            result = CreateProcess(lpApplicationName, lpCommandLine, lpProcAttribs, lpThreadAttribs, bInheritHandles,
                dwCreateFlags, lpEnvironment, lpCurrentDir, ref lpStartinfo, out lpProcInformation);
            try
            {
                Console.WriteLine("IT WOKRED!!!!!!");
            }
            catch
            {
                // swallow exceptions so that any issues caused by this code do not crash target process
            }
            return result;
        }

        static void Main(string[] args)
        {
            var p = new Program();
            p.SetupHook();

            var lpStartupInfo = new STARTUPINFO();
            var lpProcessInformation = new PROCESS_INFORMATION();
            uint flags = 0x00000000;// | DetachedProcess | CreateNoWindow;

            CreateProcess((IntPtr)0, @"notepad.exe", (IntPtr)0, (IntPtr)0,
                false, flags, (IntPtr)0, (IntPtr)0, ref lpStartupInfo, out lpProcessInformation);
            Console.WriteLine(Marshal.GetLastWin32Error());
        }

        private void SetupHook()
        {
            var createProcessHook = EasyHook.LocalHook.Create(
                                      EasyHook.LocalHook.GetProcAddress("kernel32.dll", "CreateProcessA"),
                new CreateProcess_Delegate(CreateProcess_Hook),
                this);


            createProcessHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
            Console.WriteLine("Hook Installed");
        }
    }
}
```

**Comment by Meigs2** [comment]
I fixed this issue, for anyone who can't get a callback to call, you'll need to remove the 
```csharp
createProcessHook.ThreadACL.SetExclusiveACL(new Int32[] { 0 });
```

to:
```csharp
createProcessHook.ThreadACL.SetExclusiveACL(new Int32[] { });
```
as to activate the hook on _any_ thread.

The actual callback seems to be breaking something in this specific case, but that is a different issue so I will close this issue.

**Comment by giesalabs** [comment]
Hello, 

when i hook explorer.exe PID or a testing-application this code (copy and pastle except "the main") will not show when an application is executed
am i wrong?

my main is different but it works for other hooks (example FileRead) and yes, i chenged createProcessHook.ThreadACL.SetExclusiveACL(new Int32[] { });

was you able to detect with your code the exe loading of another application or am i missing something?

**Comment by Meigs2** [comment]
I actually had some additional issues with the hook not returning correct parameters, which I will outline here, but I will reopen as my callback is still not being returned when hooked in a remote process for `CreateProcess`.

To get the callback to pass the correct parameters I had to set the delegate's `UnmanagedFunctionPointer` header to specify the Charset, like in the `DllImport` for the function import. Like so:
```csharp
[UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
```

Running my test app to open notepad works and the callback is successfully called. However when using the exact same signature in my remote target it does not work, the callback is never ran when the injected exe spawns processes with CreateProcessW. Tested with ApiMonitor, it's definitely calling CreateProcessW. See Gitter for screenshots.

Not really sure what to do now, the hook installs, and the signature works for spawning processes in my test app, but it's never called in the remote. Other functions call back fine.

**Comment by giesalabs** [comment]
i fixed by using CreateProcessW and it works fine on remote process (tested on explorer.exe)

**Comment by Meigs2** [comment]
I should definitely be watching both, but I know as a fact that CreateProcess is called in the process I am trying to hook (as I tested it with ApiMonitor), yet it never calls back like it does in my test app.

**Comment by Meigs2** [comment]
@spazzarama They are set to unicode, still does not call back from injected process.

I thought this could be caused by calling `RemoteHooking.WakeUpProcess` before installing the hooks I need, so I moved `RemoteHooking.WakeUpProcess` to AFTER where I install my windows hooks and it did not make a difference. `CreateProcessW` is still never called.

I **_have_** noticed however that it seems that `ReadFile` and `WriteFile` are being called before I call `RemoteHooking.WakeUpProcess`, aka before I finish initializing all the hooks. Strange.

**Comment by spazzarama** [comment]
@Meigs2 and you are sure it isn’t calling the ANSI string variant in this case?

**Comment by Meigs2** [comment]
@spazzarama  This signature for import delegate and callback works in my local test app which uses `Process.Start()` to use CreateProcessW to run Notepad.exe (verified with ApiMonitor). Hook calls back and the params are not mangled. This signature does NOT work within the remote I am creating with `RemoteHooking.CreateAndInject`. The other hooks from the File Monitor example on the website work, with some odd behavior as described in my last comment.

```csharp
{ (hook installation function here)
 var createProcessHook = EasyHook.LocalHook.Create(
                EasyHook.LocalHook.GetProcAddress("kernel32.dll", "CreateProcessW"),
                new CreateProcess_Delegate(CreateProcess_Hook),
                this);
 createProcessHook.ThreadACL.SetExclusiveACL(new Int32[] { });
}
...

[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        public static extern bool CreateProcessW
        (
            String lpApplicationName,
            String lpCommandLine,
            SecurityAttributes lpProcessAttributes,
            SecurityAttributes lpThreadAttributes,
            Boolean bInheritHandles,
            CreateProcessFlags dwCreationFlags,
            IntPtr lpEnvironment,
            String lpCurrentDirectory,
            [In] StartupInfo lpStartupInfo,
            out ProcessInformation lpProcessInformation
        );

        [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode, SetLastError = true)]
        delegate bool CreateProcess_Delegate(String lpApplicationName,
            String lpCommandLine,
            SecurityAttributes lpProcessAttributes,
            SecurityAttributes lpThreadAttributes,
            Boolean bInheritHandles,
            CreateProcessFlags dwCreationFlags,
            IntPtr lpEnvironment,
            String lpCurrentDirectory,
            [In] StartupInfo lpStartupInfo,
            out ProcessInformation lpProcessInformation);

        bool CreateProcess_Hook(String lpApplicationName,
            String lpCommandLine,
            SecurityAttributes lpProcessAttributes,
            SecurityAttributes lpThreadAttributes,
            Boolean bInheritHandles,
            CreateProcessFlags dwCreationFlags,
            IntPtr lpEnvironment,
            String lpCurrentDirectory,
            [In] StartupInfo lpStartupInfo,
            out ProcessInformation lpProcessInformation)
{
            bool result = false;

            result = CreateProcessW(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, 
                bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, out lpProcessInformation);
            try
            {
                _interface.Message(MessageType.Information, $"Spawned a process with CreateProcessW: {lpCommandLine}");
            }
            catch
            {
                // swallow exceptions so that any issues caused by this code do not crash target process
            }
            return result;
}
```
This is called before `RemoteHooking.WakeUpProcess`. Sorry if the formatting is messed up.

**Comment by spazzarama** [comment]
As a sanity check I would create an ansi and Unicode variant of the hook.

Also what does the rest of your Run method look like? Do you have a while loop at the end? Your hook variable appears to go out of scope, do you keep it assigned somewhere so it doesn’t get cleaned up by GC?

**Comment by Meigs2** [comment]
... well, obviously I need to keep the hooks in scope. Duh. I added them to a list that is persisted and it seems to keep the hooks installed! However, the launcher now crashes. I'll close this issue as the remote now crashes no matter what hook is installed. I appreciate the help.

**Comment by giesalabs** [comment]
if you write the CreateProcessA code can you share here please?

**Comment by giesalabs** [comment]
i tested with the List<> and CreateProcessW  and it works very well
it don't works only on some application like Firefox/Edge/Acrobat reader because are protected from hooks
