### ISSUE TITLE
Potential LhFreeMemory call on random pointer

### ISSUE THREAD

**Issue by pzychotic** [EasyHook/EasyHook#38]
Hi,

in LhAllocateHook() the variable Hook isn't initialized with NULL and the first assignment is only done after three potential THROW calls.
So we might end in the THROW_OUTRO happily passing the null pointer check and calling LhFreeMemory() on a random pointer.

**Comment by spazzarama** [comment]
Thanks @pzychotic - I've run through and checked every other compiler warning and addressed appropriately also.
