### ISSUE TITLE
How to uninstall a hook other than closing the target app?

### ISSUE THREAD

**Issue by pepeu93** [EasyHook/EasyHook#387]
In the tutorial: http://easyhook.github.io/tutorials/createlocalhook.html
There's a line with a comment:
`} // hook.Dispose() will uninstall the hook for us`

I tried to call `hook.Dispose();` but it return error: `class "_HOOK_TRACE_INFO_" has no member "Dispose"`.
I'm currently using `C++`

**EDIT**
I think I have found it:
`LhUninstallHook(&hHook);` however the dll remains attached to the target process?

**Comment by spazzarama** [comment]
The DLL will remain loaded. You will have to unload it yourself.

Also you want both:

```
// Remove the hook handler
LhUninstallHook(&hHook);

// This will restore all functions that have any 
// uninstalled hooks back to their original state.
LhWaitForPendingRemovals();
```
