### ISSUE TITLE
make the hooks permanent by modifying the binary

### ISSUE THREAD

**Issue by danyhm** [EasyHook/EasyHook#391]
Hello,

Is it possible to make the hooks permanent so we don't need an injector to hook the functions inside the binary?

I'm talking about something like microsofts detours https://github.com/microsoft/Detours/wiki/DetourBinarySetPayload which modifies the binary by editing the PE sections.

This way we don't need to inject to a remote process.

Is this possible?

**Comment by spazzarama** [comment]
EasyHook doesn’t provide this function
