### ISSUE TITLE
Error linking to easyhook32.lib

### ISSUE THREAD

**Issue by spazzarama** [EasyHook/EasyHook#4]
*Moved from [CodePlex](https://easyhook.codeplex.com/workitem/25960)
Originally submitted by DSridharC*

Hi,

I am building an app using the EasyHook 2.7 (Beta). I get the following error when I try to build it for Win32 Platform.

fatal error LNK1107: invalid or corrupt file: cannot read at 0x2D8 <<PATH to easyhook32.lib>>

In my application, I am trying to link to easyhook32.lib.

Any suggestions why this happens ?

If I compile for x64 platform, it works fine.

Thanks

**CodePlex comments**

*anroOfCode wrote May 16 at 4:20 AM
I'm seeing this too- I think the binary drop was published with the lib for static linkage.*

**Comment by kaqkk** [comment]
On my build it is not even a lib. it is a dll, renamed to lib.

**Comment by kaqkk** [comment]
In post build event for x86 configs:
copy "$(TargetPath)" "$(TargetDir)..\x64\EasyHook32.dll"
__copy "$(TargetPath)" "$(TargetDir)..\x64\EasyHook32.lib"__ -->This is probably the cause.

**Comment by spazzarama** [comment]
Lol, that will do it. Will take a look at this, probably the .lib is there and just not being copied correctly as you have pointed out.

**Comment by kaqkk** [comment]
Just submitted a patch. Could you give it  a review? Cheers!
