### ISSUE TITLE
I don't understand how to send messages back in the tutorial

### ISSUE THREAD

**Issue by Statick** [EasyHook/EasyHook#406]
Hi sorry if this is a bit of a basic level question but I really don't understand how to send messages back to the application

I'm working on the tutorial remote file monitor, the basic problem I have is that the ServerInterface which is used to communicate back to the application doesn't seem to actually do this, it simply dumps the messages out to the console. I cannot at all figure out how to instead receive messages back in my main application, I would usually use events to pass stuff around, or maybe pass an object as an argument and call methods from there, but as I cannot see an instance of ServerInterface from my application I can't see how to send stuff back from it at all. I understand I can call those methods from the injected code, but what I can't see is how I can actually retrieve data in the main application. I don't want to merely dump messages to the console output, I want some way of receiving these messages (and other data) in the main application. The ServerInterface doesn't know about my main application so it can't reference anything there, so I don't see how calling those methods can help get data back to the main application

I realise this is basic level stuff but honestly I cannot figure it out and I've spent literally all day googling this and getting nowhere

**Comment by justinstenning** [comment]
It uses .NET Framework Remoting, the FileMonInterface is passed by ref (MarshalByRefObject) to the injected module and any calls on its members actually execute in the owning process.

The instance of FileMonInterface is created within the host process (the console app) with the IpcServerChannel here: https://github.com/EasyHook/EasyHook/blob/2b048465331f7cd51774302381c3fa058e469d92/Examples/FileMon/Program.cs#L73

In the injected module (running in the targetted process), when it connects to the IPC channel, it gets a reference to the FileMonInterface: https://github.com/EasyHook/EasyHook/blob/2b048465331f7cd51774302381c3fa058e469d92/Examples/FileMonInject/Main.cs#L21

When methods of the FileMonInterface are accessed in the injected module, it actually runs within the original console process. E.g. calling Interface.OnCreateFile(..) is actually doing the equivalent of a RPC to the owning process:
https://github.com/EasyHook/EasyHook/blob/2b048465331f7cd51774302381c3fa058e469d92/Examples/FileMonInject/Main.cs#L71

Which runs the following within the host process: https://github.com/EasyHook/EasyHook/blob/2b048465331f7cd51774302381c3fa058e469d92/Examples/FileMon/Program.cs#L18-L24

**Comment by Statick** [comment]
okay, thanks, I misssed that it was being instantiated in line 73 - thanks for that

I understand that the code is executed in the main application, but it still seems isolated from the rest of the code in my main application.  I don't see how to access the instance of FileMonInterface in the main application  - it's being passed as a type into the constructor of IpcCreateChannel, and what's returned isn't an instance of FileMonInterface but an IpcChannel that doesn't seem to know or care that a FileMonInterface exists. how can I access the FileMonInterface from here? i.e from line 74 immediately after creating the IpcChannel? nothing about the IpcChannel seems to make that available to me?

specifically, in the example above, the OnCreateFile() method - instead of dumping those filenames to the console, how can I retrieve them in the main application? I still am no closer to seeing how this is possible
