### ISSUE TITLE
Any file with name of EasyLoad32.dll in the same folder with target will cause exception!

### ISSUE THREAD

**Issue by wpfpro** [EasyHook/EasyHook#41]
I've found this very very little bug by chance. And I think you may even know this but assumed that it should never happen. To me this is not a serious bug but anyway it's a bug. We can hardly encounter this bug because the condition is if there is any file with name EasyLoad32.dll (no matter it is the actual binary file EasyLoad32.dll companied with the EasyHook package or not) in the same folder with the target application (which we hook), the hook then will fail with both Inject and CreateAndInject throwing this exception: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)

 Here is the test project I've made: https://drive.google.com/file/d/0B9pRIB5Qqb08VjNxdXJwNjlTa2M/view?usp=sharing

This time I'm not very eager to wait for the bug to be fixed :)

**Comment by spazzarama** [comment]
The problem is that you have only included EasyLoad32.dll in the directory, you would also need to include at least Easyhook.dll and possibly EasyHook32.dll (might get away without this one as your injected assembly is likely the first that will need it and load from its location).

EasyLoad32.dll will load EasyHook.dll into a new AppDomain within the target process, and then load your injected .NET assembly.

**Comment by wpfpro** [comment]
I think you misunderstand the problem here. The target's folder even have the full set of binary files of EasyHook and it still throws the exception. When I say target, I mean it's the application I want to hook (not my application). You can try downloading my test project and see it in action. The Sub folder is created to mimic the situation in which there is a target application (TryExitingMe.exe) and an EasyLoad32.dll file (this file is just 0KB in my test project and does not need to be the actual EasyLoad32.dll included with EasyHook).

Now I think this should be fixed and not very little as I said. Think about this situation. The target application (we want to hook) is also an application using EasyHook, so there is a high chance that its main EXE file is in the same folder with EasyLoad32.dll

Now another application (our application used to hook the target) of course also uses EasyHook to hook that target. The exception should surely throw then (meaning it cannot hook just because of EasyLoad32.dll existing in the same folder with the target EXE file).
