### ISSUE TITLE
Trying to make EasyHook even easier but having issue with target being unhooked after the main app (server) exits?

### ISSUE THREAD

**Issue by wpfpro** [EasyHook/EasyHook#42]
I don't touch any source code of EasyHook. I just create a base class implementing IEntryPoint, it has an internal List to maintain all APIs to be hooked. The Run method then will loop through that List and create each LocalHook foreach one. 

Next time, I don't have to implement IEntryPoint, just inherit the base class I created, add custom APIs to the List and done. It works nearly perfectly but I've found that if the main app (IPC server but I call it client because it gets info from the target :) exits, the target then seems to be unhooked. Although there is not any specific code to unhook I could find. 

If implementing IEntryPoint directly (as before), the target remains hooked after the main app exits. That behavior is commonly useful so I need your help to find out what could be wrong causing this  quite strange issue. 

Here is the test project I've made: https://drive.google.com/file/d/0B9pRIB5Qqb08a3QyMlhYaldnSWs/view?usp=sharing

After running the testApp, you can try closing the target (TryExitingMe.exe), it shows that it's hooked OK. But now try exiting the main app, after that try closing the target again, it then shows that it seems to be unhooked and behaves normally (allowing to exit normally).

I hope you could help me solving this, I myself tried finding out what's wrong for a whole day but finally I had to accept that it's out of my knowledge. Thank you very much!

PS: I believe my approach would surely make it easier when working with EasyHook, so it should be supported.

**Comment by spazzarama** [comment]
I like what you are trying to do and would like to look at incorporating something similar in the project (I have a few other helpers ready also).

Anyway, back to your issue, when the host app closes the IPC channel is also closed. This means that the call to `client.Log("");` will fail.

I would do something like the following:

 1. Add a property to your base class to determine whether or not the hooks should remain if the host closes
 2. wrap the `client.Log("")` call with a try catch: e.g.
```
while(true)
{
  ...
  try 
  {
    if (client != null)
      client.Log("");
  }catch () {
    // Assume host closed
    client = null;
  }
  if (ShouldExitIfHostClosed && client == null)
    return;
...
}
```

**Comment by wpfpro** [comment]
Thank you, that's exactly what I missed. In fact the other test in which I implement IEntryPoint directly does not that `client.Log` line. That's why it worked.
