### ISSUE TITLE
No proper Run() method found

### ISSUE THREAD

**Issue by Bockey** [EasyHook/EasyHook#48]
Whenever I try to inject my dll into a process using the RemoteHooking.Inject() method I get this error message:
```
The given user library does not export a proper Run(EasyHook.InjectionLoader+REMOTE_ENTRY_INFO) method in the 'EasyHook.IEntryPoint' interface.
```

I do have a Run method though, this is how the class looks like:
```
public class Main : IEntryPoint
{
    public Main(RemoteHooking.IContext InContext, String InChannelName)
    {
            
    }
        
    public void Run(RemoteHooking.IContext InContext, String InChannelName)
    {

    }
}
```

So I don't understand why it's saying there is no run method.

**Comment by spazzarama** [comment]
What does your call to RemoteHook.Inject look like?

**Comment by Bockey** [comment]
This is the code for the injector:

```
Process[] processes;

while ((processes = Process.GetProcessesByName("ProcessName")).Length == 0)
     System.Threading.Thread.Sleep(500);

RemoteHooking.Inject(processes[0].Id,
                      "InjectedDll.dll",
                      "InjectedDll.dll",
                      null);
```

**Comment by spazzarama** [comment]
Can you please confirm the EasyHook version you are running, and also whether the ProcessMonitor.exe sample works correctly?

Do you have the EasyLoad32/64.dll binaries located in the same directory as EasyHook.dll?

Have you tried specifying the full path to your dll?

Have you tried passing in a channel name value?

**Comment by Bockey** [comment]
I tried passing in an empty string as channel name instead and it finally worked! 

Thanks xD

**Comment by spazzarama** [comment]
Ok no worries, if you don't need that parameter you can remove it also.
