### ISSUE TITLE
gdi hook not working anymore on Win10 (Build 10565)

### ISSUE THREAD

**Issue by StefanKoell** [EasyHook/EasyHook#49]
Hi,

the issue was on my end. Issue can be closed.

Regards,
Stefan

**Comment by spazzarama** [comment]
@StefanKoell anything worth sharing so others don't repeat?

**Comment by StefanKoell** [comment]
Well, it wasn't related to EasyHook at all. The GDI hook actually didn't work anymore because the rendering changed from GDI to hardware accelerated rendering (OpenGL). So no issue with EasyHook ;)

I really appreciate your work and want to thank you for providing EasyHook. Also kudos for taking care of the community here!

cheers,
Stefan

**Comment by spazzarama** [comment]
Ah, thanks Stefan.
