### ISSUE TITLE
LGPL is not compatible with many app stores

### ISSUE THREAD

**Issue by 739480474** [EasyHook/EasyHook#50]
LGPL is not compatible with online app stores, 
but, EasyHook is the only choice in .net hooking...

So, I have no choice but ask the original author of EASYHOOK.

I am linking easyhook with dynamic dlls(compiled from a modified copy of easyhook sources)

How to resolve these conficts between LGPL and app stores?
Or could you grant me a license compatiple with app stores?

Thanks.

**Comment by spazzarama** [comment]
As I understand it, as long as you are linking dynamically and provide a way for the app to be linked to a new/different version of EasyHook (i.e. have a link to your website where they could repackage the app if desired - but completely fine to be unrelated to the store), then you are complying with the licence. Here is a link that might be helpful (although Sparrow me is now owned by Google and the example that was linked is unavailable): http://roadfiresoftware.com/2013/08/the-problem-with-using-lgpl-v2-1-code-in-an-ios-app/

I'll investigate dual-licencing under certain circumstances, or to include an option to allow static linking under certain circumstances.

**Comment by 739480474** [comment]
Thanks for your reply.

As I understand it, the approuch your describled is the best way to deal with LGPL license in a app store out there.

But, it's not very perfect or very 'legal‘.
Yes, it's legal for ourselfs, but not very 'legal' for 'app store holder'(eg. apple ios store).

Because the end user just can't link/repackage the app with a new/different version of EasyHook without a iOS $99 idp key.

So, if the store accept our app(licensed with LGPL), they deprive end user of the repackge rights.
It's not very 'legal' for these stores.

Even more, the store will just reject any app licensed with LGPL in any way to avoid any legal risk, though we have did our best to deal with the 'repackage rights' of LGPL(eg, host a web site for src/obj/o, etcs).

The store don't want pay their time($) on deal with huge number of apps licensed with LGPL or its varies.

If we submit a app licensed with LGPL, it will may be accepted or just be rejected simply without reasons.

IT'S TOTALLY A GREY AREA.

I am very excited when hearing you are invesigating dual-licencing things, but why not re-license EasyHook with a diffrent easy one simply?

Best regards.

**Comment by spazzarama** [comment]
I am not the original licence holder so I can't make these decisions without some further discussion with Chris, I'll see how I go.

Re: iOS app store, you will not be able to use EasyHook there anyway as it relies on Win32 APIs, but I understand the point you are making re LGPL (I do licence all my own original work as MIT).

**Comment by 739480474** [comment]
Thanks for your reply.
You are a kind person indeed, like your code.
I am waiting for further good news. ^_^

Wish you have a nice day.

**Comment by spazzarama** [comment]
Chris agrees with changing to the MIT licence. Keep an eye on the repository for the update.

**Comment by 739480474** [comment]
BIG NEWS!! 

THANKS!!
