### ISSUE TITLE
STATUS_INVALID_PARAMETER_4: The given 32-Bit library does not exist! (Code: 2)

### ISSUE THREAD

**Issue by pana1990** [EasyHook/EasyHook#53]
I have the following code:

```c#
var ipcServer = RemoteHooking.IpcCreateServer<IModInterface>(ref ChannelName, WellKnownObjectMode.SingleCall);

                    RemoteHooking.Inject(
                        TargetPID,
                        "test.dll",
                        "test.dll",
                        ChannelName);

                } catch (Exception ExtInfo) {
                    Console.WriteLine("There was an error while connecting to target:\r\n{0}", ExtInfo.ToString());
                }
```

In RemoteHooking.inject throw the following exception 
"STATUS_INVALID_PARAMETER_4: The given 32-Bit library does not exist! (Code: 2)"

I use visual studio 2015 with 4.0 .net framework.

In my project include the following libs directly: 
```
EasyHook.dll
EasyHook32.dll
EasyHook64.dll
EasyLoad32.dll
EasyLoad64.dll
EasyHook32Svc.exe
EasyHook64Svc.exe
```
@spazzarama  Can you hel me? please.

**Comment by spazzarama** [comment]
When attempting to locate "test.dll" easyhook will be running within the target process, therefore you must either have the file on the search path (target exe, then system dirs) or provide a full path. E.g.:

                    RemoteHooking.Inject(
                        TargetPID,
                        @"c:\myproject\bin\test.dll",
                        @"c:\myproject\bin\test.dll",
                        ChannelName);

**Comment by pana1990** [comment]
My dll is in the same path as the executable

**Comment by spazzarama** [comment]
As which executable? The target process that you are injecting into?

**Comment by pana1990** [comment]
No, no. My exe is injector, for example testInjector.exe and my dll is test.dll, it is same folder,
```
testInjector.exe
test.dll
EasyHook.dll
....
```

**Comment by spazzarama** [comment]
Therefore you must specify full path to test.dll as when it is in your target it doesn't know where to look, take a look at the processmonitor or filemon examples.

**Comment by pana1990** [comment]
I have same problem with processMonitor example.

i have the following files : 

![files](https://cloud.githubusercontent.com/assets/6630197/11208898/1994b5fa-8d1e-11e5-8be3-c8bdcae1bd68.png)

When i click in item it throw exception : 

![error](https://cloud.githubusercontent.com/assets/6630197/11208975/8e967672-8d1e-11e5-8cdc-f33903e3f715.png)

what is the problem?

**Comment by spazzarama** [comment]
I don't see ProcessMonitor.exe in the list of files you have provided... If you take a look at the source of ProcMonInject.dll it references ProcessMonitor - you may need to either rename your project (I'm assuming that Example.exe is a copy of processmonitor) or you need to edit the ProcMonInject project as well.

**Comment by spazzarama** [comment]
Also take a look at the assembly binding log viewer: https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx

**Comment by pana1990** [comment]
Yes, Example.exe is copy of ProcessMonitor.exe

**Comment by spazzarama** [comment]
Ok try renaming to ProcessMonitor.exe, as mentioned the ProcMonInject.dll is referencing this assembly as this contains the definition of the IPC interface.

**Comment by pana1990** [comment]
I try renaming to ProcessMonitor but it dont works :( , it show the same error message

**Comment by spazzarama** [comment]
I would suggest trying the binaries release and make sure that is working for you.

Also use the fuslogvw.exe from the link I provided above, that will identify any issues with .NET assembly loading.

**Comment by ljani** [comment]
I had this problem. My solution was to manually remove `EasyHook` from `C:\Windows\Microsoft.NET\assembly\GAC_MSIL` (preferably your loader and agent as well). 

I was unable to get any output from `fuslogvw.exe`.

**Comment by BackTrackCRoot** [comment]
I had this problem too. but who can tell me how to fix this problem??

**Comment by BackTrackCRoot** [comment]
i forget copy EasyLoad32.dll and EasyLoad64.dll to local path................

**Comment by spazzarama** [comment]
Btw - using the NuGet package can help ensure you have the correct files being copied to the output location.

**Comment by BackTrackCRoot** [comment]
thanks, I got it~
