### ISSUE TITLE
EasyHook DLL's remain in the target process

### ISSUE THREAD

**Issue by xenolightning** [EasyHook/EasyHook#56]
After a successful hook, `Run(..)` has returned, the EasyHook DLL's remain loaded in the target process.

The culprits are:
```
EasyHook32.dll
EasyLoad32.dll
```
or
```
EasyHook64.dll
EasyLoad64.dll
```
Depending on whether the target process is 32 or 64 bit.

EasyHook.dll, and the injection host (custom dll) unload correctly.

I have been using Process Explorer from SysInternals to track what dll's are loaded/unloaded from processes.

This has been tested and reproduced with the ProcessMonitor example, and my custom hook.

Is this intentional? Is there anyway way to remove all traces of any hooks?

If this is intended behavior, feel free to close.

Custom Hook Implmentation:
https://github.com/xenolightning/AudioSwitcher/tree/AudioSession/AudioSwitcher.AudioApi.Hooking

**Comment by spazzarama** [comment]
As the EasyLoad32/64.dll .NET assemblies are loaded into the default app domain and therefore there is no way to unload them. The user assembly is loaded into a new app domain by EasyLoad and is therefore successfully unloaded when that app domain is closed.

The easyhook32/64.dll is a native DLL and is therefore able to be unloaded.

**Comment by xenolightning** [comment]
Ahh yes, Default AppDomain strikes again.

I too think it's bad practice to "unload yourself" from a process. Could cause a huge number of headaches, and potential memory addressing issues.

Good to have a concise answer, I did a fair bit of reading, but there doesn't seem to be in any doc's or issues covering this in the past.

A good assumption is the hooking process is longer running than the target process. If, for whatever reason, the hooking process is attempted to be close and deleted before the target process is closed a rule could be created to warn, and close all target processes before removal.

Thanks.

**Comment by spazzarama** [comment]
Quite a few people actually use the host process to do an inject and forget. Due to the limited impact of leaving the DLL loaded I don't think it is worth messing with, as you said, potential headaches galore (I get enough of those already! :P).
