### ISSUE TITLE
NuGet for EasyHook

### ISSUE THREAD

**Issue by spazzarama** [EasyHook/EasyHook#6]
*Moved from [CodePlex](https://easyhook.codeplex.com/workitem/63819)
Originally submitted by Cel654321*

Would it be possible to ease deployment by creating a NuGet - and this would potentially increase uptake manyfold, in general ..

**Comment by michaelpittino** [comment]
:+1

**Comment by factormystic** [comment]
:+1:

**Comment by SuicSoft** [comment]
:+1:
