### ISSUE TITLE
Get return value of a function. Do you still need the delegate?

### ISSUE THREAD

**Issue by sirjimjones** [EasyHook/EasyHook#63]
Hi,

I want to hook a function to obtain its return value. I do not want to call the function on my own. Do I still have to provide the delegate of the function? 
I got the memory address of the function and the IDA pseudo code.

Thanks!
![kegfsxv](https://cloud.githubusercontent.com/assets/11611413/12473718/2429fe4c-c015-11e5-9f3e-109e619c1d56.png)

**Comment by spazzarama** [comment]
If using EasyHook you still need to define a delegate, call the original and then you have the return value.

Looks like you have the function definition there so all good, just make sure you match the calling convention correctly.
