### ISSUE TITLE
NotSupportedException: STATUS_NOT_SUPPORTED: The caller is n ot inside a hook handler. (Code: 0)

### ISSUE THREAD

**Issue by faridaram** [EasyHook/EasyHook#68]
Hi. I written program for hooking and logging api calls. in some function call bellow lines throw following exception
Line : `Main This = (Main)HookRuntimeInfo.Callback;`
Exception : `System.NotSupportedException: STATUS_NOT_SUPPORTED: The caller is n ot inside a hook handler. (Code: 0)`

what is cause of this problem ... ?
how can i solve this problem ...

Sorry for poor english

**Comment by spazzarama** [comment]
@faridaram can you please post more of your handler code.

A common mistake is that you cannot call the original method before you request the HookRuntimeInfo.

**Comment by faridaram** [comment]
this is my hooked function :
```
int RegOpenKeyExW_Hooked(UIntPtr hKey, string subKey, int ulOptions, uint samDesired, out UIntPtr hkResult)

{
    try
    {
        string key = Enum.GetName(typeof(HKEY_TYPE), hKey.ToUInt32()) == null ? hKey.ToString() : Enum.GetName(typeof(HKEY_TYPE), hKey.ToUInt32());
        string regsam = Enum.GetName(typeof(REGSAM), samDesired) == null ? samDesired.ToString() : Enum.GetName(typeof(REGSAM), samDesired);
        List<Structures.API_PARAMETER> parameters = new List<Structures.API_PARAMETER>();
        parameters.Add(new Structures.API_PARAMETER("_In_ HKEY hKey", "HKEY", key));
        parameters.Add(new Structures.API_PARAMETER("_In_opt_ LPCTSTR lpSubKey", "LPCTSTR", subKey));
        parameters.Add(new Structures.API_PARAMETER("_In_ DWORD ulOptions", "DWORD", ulOptions.ToString()));
        parameters.Add(new Structures.API_PARAMETER("_In_ REGSAM samDesired", "REGSAM", regsam));
        parameters.Add(new Structures.API_PARAMETER("_Out_ PHKEY phkResult", "PHKEY", "[unassigned]"));
        String result = Functions.generateEntryXML(Main.index, DateTime.Now, "LONG", "WINAPI", "RegOpenKeyExW", parameters);
        main.enqueue(result);
        Main.index++;
        return RegOpenKeyExW(hKey, subKey, ulOptions, samDesired, out hkResult);
    }
    catch (Exception e)
    {
        hkResult = UIntPtr.Zero;
        return -1;
    }
}

that a function Functions.generateEntryXML only generate an xml by concatenating object values and main.enqueue function is as below :
```
public void enqueue(string data)
        {
            try
            {
                Main This = (Main)HookRuntimeInfo.Callback;
                lock (This.Queue)
                {
                    This.Queue.Enqueue(data);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());                
            }
        }


```
` Main This = (Main)HookRuntimeInfo.Callback;` where exception throws ! thanks for your help

**Comment by faridaram** [comment]
@spazzarama any suggestion ?

**Comment by spazzarama** [comment]
@faridaram can you please try getting access to the callback object as early as possible (start of the hook if you can), and then pass it through to enqueue as a parameter? If that doesn't work perhaps you could attach a simple project to reproduce the issue.
