### ISSUE TITLE
CreateAndInject failed - Beta 2.7.5558.0

### ISSUE THREAD

**Issue by spazzarama** [EasyHook/EasyHook#7]
*Moved from [CodePlex](https://easyhook.codeplex.com/workitem/63748)
Originally submitted by etommVizubi*

The same code that was working fine with the previous release, is crashing miserably with the last beta with the following error when starting with CreateAndInject

`STATUS_INTERNAL_ERROR: Unknown error in injected assembler code.`

I tryed both the source and the binary version.

**Comment by spazzarama** [comment]
See Issue #9 for the solution

**Comment by etomm** [comment]
I can confirm the problem seems solved

**Comment by jacky2050** [comment]
RhCreateAndInject for Overwatch.exe and after call it returns the error code:Unknown error in injected assembler code,but RhCreateAndInject for Wow64.exe is ok
