### ISSUE TITLE
Return value?

### ISSUE THREAD

**Issue by rjpramos** [EasyHook/EasyHook#75]
I have an old COM library that allows me to communicate with an external system. There is a simple function that takes as input a request (string) and as output a response (string). Let's say:

_string DoRequest(string request);_

This old COM library is decommissioned and, because of that, I have a lot of programs that will stop working soon that depend on that function. My idea is to hook into that function and change the way it does the requests, so that I can keep the programs running without having to code them (for some of them the source code is not available).

Now, my question is: I have already the hook working, I can hook into the function and see the parameters. The prototype of the function in C# looks like:

_string DoRequest(MyComObject obj, string request);_

However when I try to return something, it just doesn't reach the caller. My return "something" simply doesn't return the "something". Any idea of what I might be doing wrong and/or tips? Thanks in advance!

**Comment by spazzarama** [comment]
Can you show your MarshalAs attributes on the delegate etc.. 

I'm pretty sure you need to marshal as a BStr, see: http://stackoverflow.com/a/5298344/323899

**Comment by rjpramos** [comment]
Hi @spazzarama 

You are right, that was needed to make it work. I also had to prototype the function as below:

void DoRequest([In]MyComObject obj, [In]ref string request, [Out][MarshalAs(UnmanagedType.BStr)]out string output);

Thanks for the help!
