### ISSUE TITLE
Replacing a COM object

### ISSUE THREAD

**Issue by rjpramos** [EasyHook/EasyHook#81]
Hi everyone!

First, please allow me to discuss a bit my problem...

We are using an old COM object that is about to be decommissioned. That object allows some applications to communicate with our system. There are some functions that allow you to perform requests, such as:

MyReturnObject DoSomething(...);

I successfully managed to hook that function. I can, for example, access the parameters, do something about them, _call the original function_ and return MyReturnObject from the original function.

The problem is that I don't really want to call the original function (as it is not going to work anyway), I would like to instead return my own MyReturnObject filled with my properties. The problem is that I can't really create an instance of that object, I need to call the original function.

I have now 2 questions:

- Is there a way I can create my own instance of MyReturnObject, fill it with my own values and return it in such a way that the original program can use it (I already tried with reflection, deriving from the COM interfaces and a few other ways but it doesn't work, I get a COM exception)? How have you guys handled this problem?

- I believe that my approach is not that good because anyway you will have to have the old COM object installed. Most likely I should be hooking the Windows API responsible for the COM objects creation and so forth. Am I correct with this? And, if yes, can you guys point me to ways that will help me to achieve this? E.g., I was thinking if there is a tool that can analyze the COM library and generate code that would allow have the Windows API functions needed with all the needed if (guid is the one i want) then { provide my own instance } and also a tutorial on how can I create my own custom implementation of the COM library without having to register it in the Registry (hope I'm thinking well).

Thank you in advance!

**Comment by spazzarama** [comment]
@rjpramos you may need to still register your replacement COM library, I believe then it should work just with using the hook you already have in DoSomething(..) (just don't call the original). It's worth a try anyway...
