### ISSUE TITLE
I need your help.. i want to hook DeleteFile API..

### ISSUE THREAD

**Issue by gokenny21** [EasyHook/EasyHook#85]
Hi, there..
I want to use DeleteFileA, DeleteFileW API...
I made some of codes.. could you check this code?
(i can not find what is the problem...)

[Main.txt](https://github.com/EasyHook/EasyHook/files/191532/Main.txt)

**Comment by spazzarama** [comment]
I tried that code and it doesn't error out. What is happening for you?

If it is just not being called, then perhaps check with API Monitor or similar to see if that call is actually used in the target application.

I used this with Notepad++ and the DeleteFileWHook successfully fired when I closed it and it tried to cleanup some temporary files.
