### ISSUE TITLE
What possibilities of EasyHook?

### ISSUE THREAD

**Issue by 13013a** [EasyHook/EasyHook#86]
Hello. 
I began to study technologies of hook recently, for this purpose viewed several libraries. 
EasyHook seemed to me clear and easily set, but I had a question: on how many its functionality is high? 
I would like to make some check of safety for files. I.e. the user opens the file and before its direct opening something somewhere is checked, and then actually opening with the necessary parameters. I would like to make it through global Hook on CreateFile (). And so question: whether I will be able to make something similar by means of your library?

**Comment by spazzarama** [comment]
Yes you can inject into other processes and hook.

Using easyhook as a global solution may be a little difficult without using a driver - but you can do it depending on your exact requirements (I.e do u need to have hook in place before files are opened at all?). A file system filter driver is more suited to a global file auditing solution / custom access controls / whatever

**Comment by 13013a** [comment]
Hello. Thank you that answered my question.
  It seems to me that to write the driver of file system it will be complicated for me now.
And you can set some example where Hook will be set global?

**Comment by spazzarama** [comment]
@13013a  you have to enumerate all processes, and keep doing so and inject into them all.

**Comment by 13013a** [comment]
I meant property "GlobalThreadACL",I wanted to look how to use it. I correctly understood that with its help it is possible to do hook on all processes directly?

**Comment by spazzarama** [comment]
@13013a no, the thread acl is about an internal thread safety mechanism of EasyHook.

The example projects are the best place to start, just remember you may need to use the build.bat to build all the EasyHook variations required for them to run easily. Or create a new project and install the NuGet package.

**Comment by 13013a** [comment]
built.bat does nothing (perhaps it somehow on another should be launched, not simply to open?).
  I collected everything through start of EasyHook.sln with the subsequent compilation, is compiled without errors.
After that I launched FileMone.exe from the "build" folder, but after input of PID of process gives a heap of errors (the module isn't found, etc.).
If I not correctly collect something, prompt please.

**Comment by spazzarama** [comment]
@13013a if you rebuilt the entire solution for both 32- and 64-bit it should be working for you. FileMon relies on the FileMonInject project also.

**Comment by rjamesnw** [comment]
So, in lieu of a file system driver, is "enumerate all processes" still the best option today for using this?

**Comment by spazzarama** [comment]
If it's security based you will need to create a file filter driver, it also does not use hooking at all. 

Otherwise if the timing is not critical, enumerate processes, or even possibly look at using SetWindowsHookEx with a global, although that requires some dll exports (possible with C# if you use the dllexport nuget, but is more suited to native dlls) - it also might not work for all processes.

**Comment by rjamesnw** [comment]
So is there a preset function or interface that allows me to hook into all _file_ operations of a selected process?

Also, I"m assuming I can launch programs and hook into them immediately with this at least?

**Comment by spazzarama** [comment]
@rjamesnw 
No re all file operations, you need to write hook handlers for each API method you want to deal with and then install them.
You can use EasyHook's CreateAndInject to launch and immediately hook an application before it has done anything. You could perhaps hook CreateProcess and then replace with calls to CreateAndInject also, but not sure how well that will work.

**Comment by rjamesnw** [comment]
Interesting though, might be a good compromise if it works. ;)
