### ISSUE TITLE
C# DLL question

### ISSUE THREAD

**Issue by Fasjeit** [EasyHook/EasyHook#87]
Hi!
I am quite new to hooks technics and even after reading documentation I and have a question - can EasyHook hook method call from c# dll library? As I see all examplex I found only hooking c++/c methods from libraries. If so - can you give an example to redirect me to some additional reading?
ps. - The use case is hook System.IdentityModel methods.
Thanks for any reply in advance!

**Comment by spazzarama** [comment]
@Fasjeit I have never got around to looking at hooking .NET methods in detail (it used to be possible in early .NET 2 or 1 days by doing some stuff with the JIT compiler I believe). Theoretically it should be possible somehow, somewhere :)

**Comment by yazido** [comment]
I don't no if i understood you correctly. 
 **_can EasyHook hook method call from c# dll library? As I see all examplex I found only hooking c++/c methods from libraries._**
If you mean, is it possible to hook a method implemented in c# assembly => the answer is yes and there
 is many ways(using delegate, without delegate) to achieve this. I wrote an example and would upload it to  the project examples but I don't know how.

Anaway here is an example:

    public class ClassToBeHooked
    {
        public bool MethodA(int a)
        {
            Console.WriteLine("I haven't be hooked yet!");
            return true;
        }
    }

// -------------------------------------------------

static MethodADelegate LHTestHookA = new MethodADelegate(MethodAHooked);

static public bool MethodAHooked(int a)
        {
            // We aren't going to call the original at all
            // but we could using: return MessageBeep(uType);
            Console.Write("...intercepted...");
            return false;
        }

IntPtr funcPtr = typeof (ClassToBeHooked).GetMethod("MethodA").MethodHandle.GetFunctionPointer();
            LocalHook localHook2 = LocalHook.Create(
                funcPtr,
                LHTestHookA,
                null);
            localHook2.ThreadACL.SetInclusiveACL(new int[] { 0 });
            classToBeHooked.MethodA(5);

I hope that was the answer for the question you asked.

Best regards
