### ISSUE TITLE
Native hooking

### ISSUE THREAD

**Issue by maddin123** [EasyHook/EasyHook#90]
Hi,

i created a DLL project and exported the function (32 bit):
extern "C" void __declspec(dllexport) __stdcall _NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* InRemoteInfo)

then installed the hook:
FORCE(RhInjectLibrary(FindProcessId(L"TestConsole.exe"), 0, EASYHOOK_INJECT_DEFAULT, L"Inject.dll", nullptr, NULL, 0));

Then i alwyas get the error:
THROW(STATUS_INTERNAL_ERROR, L"Unable to find internal entry point.");

What i've been missing?

Regards

**Comment by spazzarama** [comment]
You should declare it as follows (note there is no underscore). The name mangling is automatic.
`extern "C" void __declspec(dllexport) __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo);`

I will create a tutorial to cover this at some point.

**Comment by maddin123** [comment]
Hi,

thank you. 

Now i get the error "Unable to find internal entry point." ?!!?

Regards

**Comment by spazzarama** [comment]
A new tutorial has been written to cover injecting remote native hooks.

http://easyhook.github.io/tutorials.html
