### ISSUE TITLE
_NativeInjectionEntryPoint@4 entry point for native apps

### ISSUE THREAD

**Issue by maddin123** [EasyHook/EasyHook#92]
>         EASYHOOK_INJECT_DEFAULT: 
            
            No special behavior. The given libraries are expected to be unmanaged DLLs.
            Further they should export an entry point named 
            "NativeInjectionEntryPoint" (in case of 64-bit) and
            "_NativeInjectionEntryPoint@4" (in case of 32-bit). The expected entry point 
            signature is REMOTE_ENTRY_POINT.

Exporting "_NativeInjectionEntryPoint@4" ist not possible as name only as "_NativeInjectionEntryPoint" because "@4" defines the ordinal and "@" is not allowed as character in the exported function name!

Regards

**Comment by spazzarama** [comment]
As per #90 the name mangling is automatic. Just use 'NativeInjectionEntryPoint' and it will be exported correctly for you in both 32- and 64-bit.
