### ISSUE TITLE
Accessing EasyHook FROM Visual Studio - C++

### ISSUE THREAD

**Issue by halbbob** [EasyHook/EasyHook#95]
Hi all,
I am just trying to run the c++ hooking example presented in http://easyhook.github.io/tutorials/nativehook.html 

I faced the below problem while trying to run this example, so could any one help?

1>4Mayhooking.obj : error LNK2019: unresolved external symbol __imp__LhWaitForPendingRemovals@0 referenced in function _wmain
1>4Mayhooking.obj : error LNK2019: unresolved external symbol __imp__LhUninstallHook@4 referenced in function _wmain
1>4Mayhooking.obj : error LNK2019: unresolved external symbol __imp__LhSetInclusiveACL@12 referenced in function _wmain
1>4Mayhooking.obj : error LNK2019: unresolved external symbol __imp__RtlGetLastErrorString@0 referenced in function _wmain
1>4Mayhooking.obj : error LNK2019: unresolved external symbol __imp__LhInstallHook@16 referenced in function _wmain

**Comment by spazzarama** [comment]
Can you create an example project and upload somewhere? I have had issues with Nuget not working every timeworn a native before too.

**Comment by halbbob** [comment]
Thanks dear
I uploaded it here
https://www.dropbox.com/s/h89gjw0mbkloifk/4Mayhooking.rar?dl=0
Thank you for your attention and consideration
Regards

**Comment by halbbob** [comment]
Hi Mr. Spazzarama 
did you consider this probelm
regards

**Comment by spazzarama** [comment]
@halbbob I downloaded it and it worked without issue. I'm using Visual Studio 2013.

**Comment by spazzarama** [comment]
I think the NuGet might need some more work to work across additional Visual Studio versions...

**Comment by spazzarama** [comment]
It will work if you manually add EasyHook32.lib to your project:

 1. add to your "VC++ Directories -> Library Directories": `..\packages\EasyHookNativePackage.2.7.5870.1\build\native\lib\Win32\v120\Debug;`
 2. add to your "Linker\Input\Additional Dependencies": EasyHook32.lib

**Comment by halbbob** [comment]
Thank you so much Mr. Spazzarama for your attention and support, now it is working. After adding Eashhook64.lib and easyhook64.dll to my project as you said.

I need your suggestion on my current work. In fact, I am doing a research that prevents a user from wiping a file (using wiping tools such as CClenaer) so I need to:

1. - First, hook a system call called by the CClenaer (mainly WrtieFile) so the targeted file is not wiped. We can let the system do our own Writefile function.
2. - Second, wrapping (hidden the file when the user open its corresponding folder) so the user relay think that the fil

e was successflly wiped while the file is still exist.

Can you give me your suggestions. Your suggestions (or a road map) will save a lot of time for me.

Thanks again dear
Regards

**Comment by spazzarama** [comment]
If you are targeting a specific process, or couple of processes, then use API Monitor to check what operations you want to intercept, then write hooks for those.

If you want to do a system wide protection of specific files you will need to use a File Filter Driver instead.

**Comment by halbbob** [comment]
In fact, I am working with the first direction. I used the ProcessMonitor to list all system calls used by a process. Then, I am using EasyHook to hook the identified system calls. So, can I hook - from my code below - a Writefile operation called by another software. Is there anything I have to do with this line:
ULONG ACLEntries[1] = { 0 **};**

The below code is not working can you check it please. my myWriteFileHook function hooks the WriteFile by writing into a temp file


#include "stdafx.h"
#include "string"
#include <iostream>
#include "easyhook.h"
#include "Windows.h"
#include <stdio.h>
#include <conio.h>
#include<stdlib.h>

#ifndef _M_X64
    #pragma comment(lib, "EasyHook32.lib")
#else
    #pragma comment(lib, "EasyHook64.lib")
#endif

#pragma warning(disable: 4100 4127)

#define FORCE(expr)     {if(!SUCCEEDED(NtStatus = (expr))) goto ERROR_ABORT;}


BOOL WINAPI myWriteFileHook(
  _In_        HANDLE       hFile,
  _In_        LPCVOID      lpBuffer,
  _In_        DWORD        nNumberOfBytesToWrite,
  _Out_opt_   LPDWORD      lpNumberOfBytesWritten,
  _Inout_opt_ LPOVERLAPPED lpOverlapped
);
BOOL WINAPI myWriteFileHook(
  _In_        HANDLE       hFile,
  _In_        LPCVOID      lpBuffer,
  _In_        DWORD        nNumberOfBytesToWrite,
  _Out_opt_   LPDWORD      lpNumberOfBytesWritten,
  _Inout_opt_ LPOVERLAPPED lpOverlapped
){
	
    TCHAR szTempFileName[260]=TEXT("Desert.jpg");
	std::cout << "\nHALBOOB";
	std::wcout << szTempFileName ;
	return WriteFile( szTempFileName,lpBuffer,  nNumberOfBytesToWrite,lpNumberOfBytesWritten,lpOverlapped);
	 }
extern "C" int main(int argc, wchar_t* argv[])
{
    HOOK_TRACE_INFO hHook = { NULL }; // keep track of our hook
    std::cout << "pBeep";
    std::cout << "\n";
    std::cout << GetProcAddress(GetModuleHandle(TEXT("kernel32")), "WriteFile");
    
    
	// Install the hook
    NTSTATUS result = LhInstallHook(
        GetProcAddress(GetModuleHandle(TEXT("Kernel32")), "WriteFile"), 
		
        myWriteFileHook, 
		 NULL, 
        &hHook);
    if (FAILED(result))
    {
        std::wstring s(RtlGetLastErrorString());
        std:: wcout << "Failed to install hook: ";
        std::wcout << s;
        std::cout << "\n\nPress any key to exit.";
        std::cin.get();
        return -1;
    }
    
    std::cout << "Beep after hook installed but not enabled.\n";
    Beep(500, 500);

    std::cout << "Activating hook for current thread only.\n";
    // If the threadId in the ACL is set to 0, 
    // then internally EasyHook uses GetCurrentThreadId()
    ULONG ACLEntries[1] = { 0 };
    LhSetInclusiveACL(ACLEntries, 1, &hHook);

    std::cout << "Beep after hook enabled.\n";
    Beep(500, 500);

   /* std::cout << "Uninstall hook\n";
    LhUninstallHook(&hHook);

    std::cout << "Beep after hook uninstalled\n";
    Beep(500, 500);

    std::cout << "\n\nRestore ALL entry points of pending removals issued by LhUninstallHook()\n";
    LhWaitForPendingRemovals();*/

    std::cout << "Press any key to exit.";
    std::cin.get();

    return 0;
}

**Comment by spazzarama** [comment]
You need to use RhInjectLibrary to inject it into the target process first:
`RhInjectLibrary(processID, 0, EASYHOOK_INJECT_DEFAULT, L"MyInjectLibrary.dll", nullptr, NULL, 0);`

**Comment by halbbob** [comment]
thank you dear
I am going to try it
Regards

**Comment by spazzarama** [comment]
Your DLL also needs to export an entry point like this:
```cpp
extern "C" void __declspec(dllexport) __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo);

void __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo)
{
	
	// Perform hooking

	return;
}
```

**Comment by halbbob** [comment]
Thanks Mr. Spazzarama again for your attention 
I made my DLL project as you suggest

Now, where do I have to use the hooking function (below). Do I need to put it here

void __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo)
{

    // Perform hooking

    return;
} 


Below is my hooking function and it is now inside the console application:

BOOL WINAPI myWriteFileHook(
In HANDLE hFile,
In LPCVOID lpBuffer,
In DWORD nNumberOfBytesToWrite,
Out_opt LPDWORD lpNumberOfBytesWritten,
Inout_opt LPOVERLAPPED lpOverlapped
);
BOOL WINAPI myWriteFileHook(
In HANDLE hFile,
In LPCVOID lpBuffer,
In DWORD nNumberOfBytesToWrite,
Out_opt LPDWORD lpNumberOfBytesWritten,
Inout_opt LPOVERLAPPED lpOverlapped
){

TCHAR szTempFileName[260]=TEXT("Desert.jpg");
std::cout << "\nHALBOOB";
std::wcout << szTempFileName ;
return WriteFile( szTempFileName,lpBuffer,  nNumberOfBytesToWrite,lpNumberOfBytesWritten,lpOverlapped);
 }

**Comment by spazzarama** [comment]
The hooks should be installed from NativeInjectionEntryPoint in your DLL project

**Comment by spazzarama** [comment]
Tutorials added to cover this:

http://easyhook.github.io/tutorials.html
