### ISSUE TITLE
I can Inject code HTML to Browser(Chrome) ? 

### ISSUE THREAD

**Issue by RedToor** [EasyHook/EasyHook#96]
I'm trying make a software to _inject code_ in web pages, with this library is possible through of Dll injection, 

Thanks so much in advance.

**Comment by spazzarama** [comment]
Yes you can inject a dll into Chrome

**Comment by RedToor** [comment]
Ok, i'll test it, Thansk so much.

**Comment by jawandsingh** [comment]
@spazzarama & @RedToor can you guide me in the right direction. I am kind of a noob on low-level stuff.
