### ISSUE TITLE
"Unable to find internal entry point."

### ISSUE THREAD

**Issue by maddin123** [EasyHook/EasyHook#97]
Hi,

I get the error "Unable to find internal entry point." ?!!?
What might be the problem? Calling convention?

Regards

**Comment by spazzarama** [comment]
This works fine here:

In the DLL:
```cpp
extern "C" void __declspec(dllexport) __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo);

void __stdcall NativeInjectionEntryPoint(REMOTE_ENTRY_INFO* inRemoteInfo)
{
	Beep(500, 1000);
	return;
}
```

In my console app:
```
RhInjectLibrary(processID, 0, EASYHOOK_INJECT_DEFAULT, L"Win32Project1.dll", nullptr, NULL, 0);
```

Where Win32Project1.dll is my DLL and they are both in the same directory. They are both also using the EasyHook Native NuGet package, and I'm using Visual Studio 2013.

**Comment by maddin123** [comment]
Hi,

I downloaded your git source from here, why NuGet???

I'm using VS2010 - that's not working, VS2015 is not working too, becuase your native package uses VS2013!

**Comment by spazzarama** [comment]
For NuGet in other VS versions, look at issue #94

**Comment by spazzarama** [comment]
Btw the "Unable to find internal entry point." error means that ASM injection code was unable to find the "HookCompleteInjection" export within the EasyHook32/64.dll.

This could be because the GetProcAddress failed for some reason, or something is wrong with the dll. At this point it should have loaded the DLL correctly however, so it is a bit odd.

Can you try one of the examples on the same target and see if that succeeds?

**Comment by maddin123** [comment]
Hi Spazza,

could you please provide a very simple native remote injection example? BTW this would be for all users of the library. I only found a local injection example which is not sifficiant for my needs.

The example should work from VS2010 and up without NuGet.

Just put the sample into the source on Github. Please test it with the sources on Github.

Thanks in advance!

Regards
Martin

**Comment by spazzarama** [comment]
Two new tutorials have been written to cover remote injection and also for manually installing EasyHook into a sample project.

http://easyhook.github.io/tutorials.html
